"""Emit-focused checks for pathological stress fixtures."""

from __future__ import annotations

from pathlib import Path

import pytest

from mojo_bindgen.codegen.generator import MojoGenerator
from mojo_bindgen.codegen.mojo_emit_options import MojoEmitOptions
from tests.stress._helpers import case_dirs, has_libclang, parse_case

_REPO_ROOT = Path(__file__).resolve().parents[2]

pytestmark = pytest.mark.skipif(
    not has_libclang(),
    reason="libclang not available (use pixi run)",
)


@pytest.mark.parametrize("case_dir", case_dirs(), ids=lambda path: path.name)
def test_stress_fixture_emits_non_empty_source(
    case_dir,
) -> None:
    unit = parse_case(case_dir)
    out = MojoGenerator(MojoEmitOptions()).generate(unit)

    assert out.strip()
    assert "# Generated by mojo_bindgen" in out
    assert f"# source: {case_dir / 'input.h'}" in out
    assert f"# library: {case_dir.name}  link_name: {case_dir.name}" in out
    assert "struct " in out or "alias " in out or "comptime " in out
