"""Pretty-print normalized MojoIR to Mojo source."""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass

from mojo_bindgen.analysis.common import mojo_float_literal_text, mojo_ident
from mojo_bindgen.codegen.normalize_mojo_module import normalize_mojo_module
from mojo_bindgen.mojo_ir import (
    AliasDecl,
    AliasKind,
    ArrayType,
    BitfieldGroupMember,
    BuiltinType,
    CallbackParam,
    CallbackType,
    CallTarget,
    EnumDecl,
    FunctionDecl,
    FunctionKind,
    GlobalDecl,
    GlobalKind,
    Initializer,
    LinkMode,
    LoweringNote,
    ModuleImport,
    MojoBinaryExpr,
    MojoBuiltin,
    MojoCastExpr,
    MojoCharLiteral,
    MojoConstExpr,
    MojoDecl,
    MojoFloatLiteral,
    MojoIntLiteral,
    MojoModule,
    MojoRefExpr,
    MojoSizeOfExpr,
    MojoStringLiteral,
    MojoType,
    MojoUnaryExpr,
    NamedType,
    OpaqueStorageMember,
    ParametricBase,
    ParametricType,
    PointerMutability,
    PointerOrigin,
    PointerType,
    StoredMember,
    StructDecl,
    StructKind,
    SupportDeclKind,
)


@dataclass(frozen=True)
class MojoIRPrintOptions:
    module_comment: bool = True


class MojoIRPrintError(ValueError):
    """Raised when normalized MojoIR cannot be rendered as valid Mojo source."""


class CodeBuilder:
    """Indented line buffer for Mojo source emission."""

    def __init__(self) -> None:
        self._lines: list[str] = []
        self._level = 0

    def indent(self) -> None:
        self._level += 1

    def dedent(self) -> None:
        self._level = max(0, self._level - 1)

    def add(self, line: str) -> None:
        self._lines.append("    " * self._level + line)

    def extend(self, lines: Iterable[str]) -> None:
        for line in lines:
            self.add(line)

    def render(self) -> str:
        return "" if not self._lines else "\n".join(self._lines)


class MojoIRPrinter:
    """Render normalized :class:`~mojo_bindgen.mojo_ir.MojoModule` to source text."""

    def __init__(self, options: MojoIRPrintOptions | None = None) -> None:
        self._options = options or MojoIRPrintOptions()

    @property
    def options(self) -> MojoIRPrintOptions:
        return self._options

    def render(self, module: MojoModule) -> str:
        parts: list[str] = []
        if self._options.module_comment:
            parts.append(self._render_module_header(module))
        if module.imports:
            parts.append(self._render_import_block(module.imports))
        support_block = self._render_support_decls(module)
        if support_block:
            parts.append(support_block)
        parts.extend(self._render_decl(decl) for decl in module.decls)
        return "\n\n".join(chunk for chunk in parts if chunk) + ("\n" if parts else "")

    def _render_module_header(self, module: MojoModule) -> str:
        return "\n".join(
            [
                "# Generated by mojo_bindgen - do not edit by hand.",
                f"# source: {module.source_header}",
                f"# library: {module.library}  link_name: {module.link_name}",
                f"# FFI mode: {module.link_mode.value}",
            ]
        )

    @staticmethod
    def _render_import_block(imports: list[ModuleImport]) -> str:
        lines = [f"from {imp.module} import {', '.join(imp.names)}" for imp in imports]
        return "\n".join(lines)

    def _render_support_decls(self, module: MojoModule) -> str:
        chunks: list[str] = []
        for support in module.support_decls:
            if support.kind == SupportDeclKind.DL_HANDLE_HELPERS:
                chunks.append(self._render_dl_handle_helper(module))
            elif support.kind == SupportDeclKind.GLOBAL_SYMBOL_HELPERS:
                chunks.append(
                    "struct GlobalVar[T: Copyable & ImplicitlyDestructible, //, link: StaticString]:\n"
                    "    @staticmethod\n"
                    "    def _raw() raises -> UnsafePointer[Self.T, MutAnyOrigin]:\n"
                    "        var opt: Optional[UnsafePointer[Self.T, MutAnyOrigin]] = _bindgen_dl().get_symbol[Self.T](StringSlice(Self.link))\n"
                    "        if not opt:\n"
                    '            raise Error(String("bindgen: missing C global symbol"))\n'
                    "        return opt.value()\n"
                    "\n"
                    "    @staticmethod\n"
                    "    def ptr() raises -> UnsafePointer[Self.T, MutExternalOrigin]:\n"
                    "        return rebind[UnsafePointer[Self.T, MutExternalOrigin]](Self._raw())\n"
                    "\n"
                    "    @staticmethod\n"
                    "    def load() raises -> Self.T:\n"
                    "        return Self._raw()[].copy()\n"
                    "\n"
                    "    @staticmethod\n"
                    "    def store(value: Self.T) raises -> None:\n"
                    "        var p = rebind[UnsafePointer[Self.T, MutExternalOrigin]](Self._raw())\n"
                    "        p[] = value.copy()\n"
                    "\n"
                    "struct GlobalConst[T: Copyable & ImplicitlyDestructible, //, link: StaticString]:\n"
                    "    @staticmethod\n"
                    "    def _raw() raises -> UnsafePointer[Self.T, MutAnyOrigin]:\n"
                    "        var opt: Optional[UnsafePointer[Self.T, MutAnyOrigin]] = _bindgen_dl().get_symbol[Self.T](StringSlice(Self.link))\n"
                    "        if not opt:\n"
                    '            raise Error(String("bindgen: missing C global symbol"))\n'
                    "        return opt.value()\n"
                    "\n"
                    "    @staticmethod\n"
                    "    def ptr() raises -> UnsafePointer[Self.T, ImmutExternalOrigin]:\n"
                    "        return rebind[UnsafePointer[Self.T, ImmutExternalOrigin]](Self._raw())\n"
                    "\n"
                    "    @staticmethod\n"
                    "    def load() raises -> Self.T:\n"
                    "        return Self._raw()[].copy()"
                )
            else:
                raise MojoIRPrintError(f"unsupported SupportDecl kind: {support.kind!r}")
        return "\n\n".join(chunks)

    @staticmethod
    def _render_dl_handle_helper(module: MojoModule) -> str:
        if module.link_mode == LinkMode.OWNED_DL_HANDLE and module.library_path_hint is not None:
            path_lit = module.library_path_hint.replace("\\", "\\\\").replace('"', '\\"')
            return (
                f'comptime _BINDGEN_LIB_PATH: String = "{path_lit}"\n'
                "\n"
                "def _bindgen_dl() raises -> OwnedDLHandle:\n"
                "    return OwnedDLHandle(_BINDGEN_LIB_PATH)"
            )
        return (
            "# Resolve symbols from libraries already linked into this process.\n"
            "def _bindgen_dl() raises -> OwnedDLHandle:\n"
            "    return OwnedDLHandle(DEFAULT_RTLD)"
        )

    def _render_decl(self, decl: MojoDecl) -> str:
        if isinstance(decl, StructDecl):
            return self._render_struct_decl(decl)
        if isinstance(decl, EnumDecl):
            return self._render_enum_decl(decl)
        if isinstance(decl, AliasDecl):
            return self._render_alias_decl(decl)
        if isinstance(decl, FunctionDecl):
            return self._render_function_decl(decl)
        if isinstance(decl, GlobalDecl):
            return self._render_global_decl(decl)
        raise MojoIRPrintError(f"unsupported MojoDecl node: {type(decl).__name__!r}")

    # TODO: Revise traits
    def _render_struct_decl(self, decl: StructDecl) -> str:
        b = CodeBuilder()
        b.extend(self._diagnostic_lines(decl.diagnostics))
        if decl.align_decorator is not None:
            b.add(f"@align({decl.align_decorator})")
        if decl.fieldwise_init:
            b.add("@fieldwise_init")

        traits = list(decl.traits)
        if decl.kind == StructKind.OPAQUE and not traits:
            traits = ["Copyable", "Movable"]
        trait_text = f"({', '.join(traits)})" if traits else ""
        b.add(f"struct {decl.name}{trait_text}:")
        b.indent()
        if decl.kind == StructKind.OPAQUE:
            b.add("pass")
        else:
            self._render_plain_struct_body(b, decl)
        b.dedent()
        return b.render()

    def _render_enum_decl(self, decl: EnumDecl) -> str:
        b = CodeBuilder()
        b.extend(self._diagnostic_lines(decl.diagnostics))
        if decl.align_decorator is not None:
            b.add(f"@align({decl.align_decorator})")
        if decl.fieldwise_init:
            b.add("@fieldwise_init")
        b.add("struct " + decl.name + "(Copyable, Movable, RegisterPassable):")
        b.indent()
        base_text = self._render_type(decl.underlying_type)
        b.add(f"var value: {base_text}")
        for member in decl.enumerants:
            b.add(f"comptime {member.name} = Self({base_text}({member.value}))")
        b.dedent()
        return b.render()

    def _render_plain_struct_body(self, b: CodeBuilder, decl: StructDecl) -> None:
        if not decl.members and not decl.initializers:
            b.add("pass")
            return

        bitfield_names = {
            field.name
            for member in decl.members
            if isinstance(member, BitfieldGroupMember)
            for field in member.fields
        }
        bitfield_storage_types = {
            member.storage_name: self._render_type(member.storage_type)
            for member in decl.members
            if isinstance(member, BitfieldGroupMember)
        }

        for member in decl.members:
            if isinstance(member, StoredMember):
                b.add(f"var {member.name}: {self._render_type(member.type)}")
            elif isinstance(member, OpaqueStorageMember):
                b.add(f"var {member.name}: InlineArray[UInt8, {member.size_bytes}]")
            elif isinstance(member, BitfieldGroupMember):
                b.add(f"var {member.storage_name}: {self._render_type(member.storage_type)}")
            else:
                b.add(f"var {member.name}: InlineArray[UInt8, {member.size_bytes}]")

        for initializer in decl.initializers:
            self._render_initializer(
                b,
                initializer,
                bitfield_names,
                bitfield_storage_types,
            )
        for member in decl.members:
            if isinstance(member, BitfieldGroupMember):
                self._render_bitfield_group_accessors(b, member)

    def _render_initializer(
        self,
        b: CodeBuilder,
        initializer: Initializer,
        bitfield_names: set[str],
        bitfield_storage_types: dict[str, str],
    ) -> None:
        params = ", ".join(
            f"{self._render_param_name(param.name, i)}: {self._render_type(param.type)}"
            for i, param in enumerate(initializer.params)
        )
        b.add(f"def __init__(out self{', ' if params else ''}{params}):")
        b.indent()
        for storage_name, storage_type in bitfield_storage_types.items():
            b.add(f"self.{storage_name} = {storage_type}(0)")
        for i, param in enumerate(initializer.params):
            param_name = self._render_param_name(param.name, i)
            if param_name in bitfield_names:
                b.add(f"self.set_{param_name}({param_name})")
            else:
                b.add(f"self.{param_name} = {param_name}")
        b.dedent()

    def _render_bitfield_group_accessors(
        self,
        b: CodeBuilder,
        group: BitfieldGroupMember,
    ) -> None:
        storage_type = self._render_type(group.storage_type)
        for bitfield in group.fields:
            logical_type = self._render_type(bitfield.logical_type)
            mask_text = self._storage_mask_text(bitfield.bit_width)
            shift = max(0, bitfield.bit_offset - group.byte_offset * 8)
            b.add(f"def {bitfield.name}(self) -> {logical_type}:")
            b.indent()
            b.add(f"var raw = (self.{group.storage_name} >> {shift}) & {storage_type}({mask_text})")
            if bitfield.bool_semantics:
                b.add(f"return raw != {storage_type}(0)")
            elif bitfield.signed and bitfield.bit_width > 0:
                sign_bit_text = hex(1 << (bitfield.bit_width - 1))
                b.add(f"if raw & {storage_type}({sign_bit_text}) != {storage_type}(0):")
                b.indent()
                b.add(f"return {logical_type}(raw | ~{storage_type}({mask_text}))")
                b.dedent()
                b.add(f"return {logical_type}(raw)")
            else:
                b.add(f"return {logical_type}(raw)")
            b.dedent()
            b.add(f"def set_{bitfield.name}(mut self, value: {logical_type}):")
            b.indent()
            if bitfield.bool_semantics:
                b.add(f"var raw_value = {storage_type}(1) if value else {storage_type}(0)")
            else:
                b.add(f"var raw_value = {storage_type}(value) & {storage_type}({mask_text})")
            b.add(f"var clear_mask = ~({storage_type}({mask_text}) << {shift})")
            b.add(
                f"self.{group.storage_name} = (self.{group.storage_name} & clear_mask) | "
                f"((raw_value & {storage_type}({mask_text})) << {shift})"
            )
            b.dedent()

    def _render_alias_decl(self, decl: AliasDecl) -> str:
        b = CodeBuilder()
        macro_comment_lines = [
            f"# {note.message}" for note in decl.diagnostics if note.category == "macro_comment"
        ]
        non_macro_notes = [note for note in decl.diagnostics if note.category != "macro_comment"]
        b.extend(self._diagnostic_lines(non_macro_notes))
        if decl.kind == AliasKind.CALLBACK_SIGNATURE:
            if not isinstance(decl.type_value, CallbackType):
                raise MojoIRPrintError(
                    f"callback alias {decl.name!r} is missing normalized CallbackType payload"
                )
            b.add(f"comptime {decl.name} = {self._render_callback_signature(decl.type_value)}")
            return b.render()

        if decl.type_value is not None:
            b.add(f"comptime {decl.name} = {self._render_type(decl.type_value)}")
        elif decl.const_value is not None:
            b.add(f"comptime {decl.name} = {self._render_const_expr(decl.const_value)}")
        elif decl.kind == AliasKind.MACRO_VALUE and macro_comment_lines:
            b.extend(macro_comment_lines)
        else:
            b.add(f"# alias {decl.name}: missing payload")
        return b.render()

    def _render_function_decl(self, decl: FunctionDecl) -> str:
        b = CodeBuilder()
        b.extend(self._diagnostic_lines(decl.diagnostics))
        params = [
            f"{self._render_param_name(param.name, i)}: {self._render_type(param.type)}"
            for i, param in enumerate(decl.params)
        ]
        params_text = ", ".join(params)
        return_type = self._render_type(decl.return_type)
        symbol = self._link_symbol(decl.call_target, decl.link_name)
        bracket_inner = ", ".join(
            [f'"{symbol}"', return_type] + [self._render_type(param.type) for param in decl.params]
        )
        call_args = ", ".join(
            self._render_param_name(param.name, i) for i, param in enumerate(decl.params)
        )

        if decl.kind == FunctionKind.VARIADIC_STUB:
            b.add("# variadic C function - not callable from thin FFI:")
            b.add(f"# {return_type} {symbol}({params_text}, ...)")
            return b.render()
        if decl.kind == FunctionKind.NON_REGISTER_RETURN_STUB:
            b.add(
                "# C return type is not RegisterPassable - external_call cannot model this return; bind manually."
            )
            b.add(f"# {return_type} {symbol}({params_text})")
            return b.render()

        if decl.call_target.link_mode == LinkMode.EXTERNAL_CALL:
            if return_type == "NoneType":
                b.add(f'def {decl.name}({params_text}) abi("C") -> None:')
                b.indent()
                b.add(f"external_call[{bracket_inner}]({call_args})")
            else:
                b.add(f'def {decl.name}({params_text}) abi("C") -> {return_type}:')
                b.indent()
                b.add(f"return external_call[{bracket_inner}]({call_args})")
        else:
            if return_type == "NoneType":
                b.add(f"def {decl.name}({params_text}) raises -> None:")
                b.indent()
                b.add(f"_bindgen_dl().call[{bracket_inner}]({call_args})")
            else:
                b.add(f"def {decl.name}({params_text}) raises -> {return_type}:")
                b.indent()
                b.add(f"return _bindgen_dl().call[{bracket_inner}]({call_args})")
        b.dedent()
        return b.render()

    def _render_global_decl(self, decl: GlobalDecl) -> str:
        b = CodeBuilder()
        b.extend(self._diagnostic_lines(decl.diagnostics))
        value_type = self._render_type(decl.value_type)
        if decl.kind == GlobalKind.STUB:
            if (
                isinstance(decl.value_type, ParametricType)
                and decl.value_type.base == ParametricBase.ATOMIC
            ):
                b.add(
                    f"# global variable {decl.link_name}: {value_type} (atomic global requires manual binding (use Atomic APIs on a pointer))"
                )
                return b.render()
            const_kw = "const " if decl.is_const else ""
            b.add(
                f"# global variable {decl.link_name}: {const_kw}{value_type} (manual binding required)"
            )
            return b.render()

        wrapper = "GlobalConst" if decl.is_const else "GlobalVar"
        link_lit = decl.link_name.replace("\\", "\\\\").replace('"', '\\"')
        b.add(f"# global `{decl.link_name}` -> {value_type}")
        b.add(f'comptime {decl.name} = {wrapper}[T={value_type}, link="{link_lit}"]')
        return b.render()

    def _render_type(self, t: MojoType) -> str:
        if isinstance(t, BuiltinType):
            if t.name == MojoBuiltin.UNSUPPORTED:
                raise MojoIRPrintError("cannot render MojoBuiltin.UNSUPPORTED as valid Mojo")
            return t.name.value
        if isinstance(t, NamedType):
            return t.name
        if isinstance(t, PointerType):
            return self._render_pointer_type(t)
        if isinstance(t, ArrayType):
            return f"InlineArray[{self._render_type(t.element)}, {t.count}]"
        if isinstance(t, ParametricType):
            args = ", ".join(self._render_parametric_arg(arg) for arg in t.args)
            return f"{t.base.value}[{args}]"
        if isinstance(t, CallbackType):
            return self._render_callback_signature(t)
        raise MojoIRPrintError(f"unsupported MojoType node: {type(t).__name__!r}")

    def _render_pointer_type(self, t: PointerType) -> str:
        if t.pointee is None:
            ptr_name = (
                "ImmutOpaquePointer"
                if t.mutability == PointerMutability.IMMUT
                else "MutOpaquePointer"
            )
            return f"{ptr_name}[{self._origin_name(t.origin, t.mutability)}]"
        return f"UnsafePointer[{self._render_type(t.pointee)}, {self._origin_name(t.origin, t.mutability)}]"

    def _render_parametric_arg(self, arg: object) -> str:
        from mojo_bindgen.mojo_ir import ConstArg, DTypeArg, NameArg, TypeArg

        if isinstance(arg, DTypeArg):
            return arg.value
        if isinstance(arg, ConstArg):
            return str(arg.value)
        if isinstance(arg, NameArg):
            return arg.value
        if isinstance(arg, TypeArg):
            return self._render_type(arg.type)
        raise MojoIRPrintError(f"unsupported parametric argument node: {type(arg).__name__!r}")

    def _render_callback_signature(self, callback: CallbackType) -> str:
        params = ", ".join(
            f"{self._render_callback_param_name(param, i)}: {self._render_type(param.type)}"
            for i, param in enumerate(callback.params)
        )
        ret = self._render_type(callback.ret)
        parts = ["def", f"({params})"]
        if callback.thin:
            parts.append("thin")
        if callback.abi:
            parts.append(f'abi("{callback.abi}")')
        if callback.raises:
            parts.append("raises")
        parts.extend(["->", ret])
        return " ".join(parts)

    def _render_const_expr(self, expr: MojoConstExpr) -> str:
        if isinstance(expr, MojoIntLiteral):
            return str(expr.value)
        if isinstance(expr, MojoFloatLiteral):
            return mojo_float_literal_text(str(expr.value))
        if isinstance(expr, MojoStringLiteral):
            return '"' + expr.value.replace("\\", "\\\\").replace('"', '\\"') + '"'
        if isinstance(expr, MojoCharLiteral):
            return "'" + expr.value.replace("\\", "\\\\").replace("'", "\\'") + "'"
        if isinstance(expr, MojoRefExpr):
            return expr.name
        if isinstance(expr, MojoUnaryExpr):
            return f"{expr.op}({self._render_const_expr(expr.operand)})"
        if isinstance(expr, MojoBinaryExpr):
            lhs = self._render_const_expr(expr.lhs)
            rhs = self._render_const_expr(expr.rhs)
            return f"({lhs} {expr.op} {rhs})"
        if isinstance(expr, MojoCastExpr):
            return f"{self._render_type(expr.target)}({self._render_const_expr(expr.expr)})"
        if isinstance(expr, MojoSizeOfExpr):
            return f"__builtin_sizeof[{self._render_type(expr.target)}]()"
        raise MojoIRPrintError(f"unsupported MojoConstExpr node: {type(expr).__name__!r}")

    @staticmethod
    def _diagnostic_lines(notes: Iterable[LoweringNote]) -> list[str]:
        return [
            f"# {note.severity.value.upper()}[{note.category}]: {note.message}" for note in notes
        ]

    @staticmethod
    def _render_param_name(name: str, index: int) -> str:
        if name.strip():
            return mojo_ident(name)
        return f"a{index}"

    @staticmethod
    def _render_callback_param_name(param: CallbackParam, index: int) -> str:
        if param.name.strip():
            return mojo_ident(param.name, fallback=f"arg{index}")
        return f"arg{index}"

    @staticmethod
    def _origin_name(origin: PointerOrigin, mutability: PointerMutability) -> str:
        if origin == PointerOrigin.ANY:
            return "ImmutAnyOrigin" if mutability == PointerMutability.IMMUT else "MutAnyOrigin"
        return (
            "ImmutExternalOrigin" if mutability == PointerMutability.IMMUT else "MutExternalOrigin"
        )

    @staticmethod
    def _storage_mask_text(width: int) -> str:
        if width <= 0:
            return "0"
        return hex((1 << width) - 1)

    @staticmethod
    def _link_symbol(call_target: CallTarget, fallback: str) -> str:
        return call_target.symbol or fallback


def render_mojo_module(
    module: MojoModule,
    options: MojoIRPrintOptions | None = None,
) -> str:
    """Normalize and render a standalone :class:`MojoModule` to Mojo source."""

    normalized = normalize_mojo_module(module)
    return MojoIRPrinter(options).render(normalized)


__all__ = [
    "MojoIRPrintError",
    "MojoIRPrinter",
    "MojoIRPrintOptions",
    "render_mojo_module",
]
