# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/macro_literals/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call
from std.ffi import external_call

comptime MLI_INT = Int32(7)

comptime MLI_FLOAT = 3.5

comptime MLI_CHAR = 'x'

comptime MLI_STRING = "bindgen"

