# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/macro_literals/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import c_int

comptime MLI_INT = c_int(7)

comptime MLI_FLOAT = 3.5

comptime MLI_CHAR = 'x'

comptime MLI_STRING = "bindgen"
