# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/enum_namespace_rules/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call, c_uint

comptime TAG_A = typedef_name(c_uint(3))

comptime MODE_A = enum_mode_tag(c_uint(1))

@fieldwise_init
struct typedef_name(Copyable, Movable, RegisterPassable):
    var value: c_uint

@fieldwise_init
struct enum_mode_tag(Copyable, Movable, RegisterPassable):
    var value: c_uint

def take_typedef_name(mode: typedef_name) abi("C") -> typedef_name:
    return external_call["take_typedef_name", typedef_name, typedef_name](mode)

def get_mode_tag() abi("C") -> enum_mode_tag:
    return external_call["get_mode_tag", enum_mode_tag]()
