# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/macro_comments/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call
from std.ffi import external_call

# macro MCC_FILE: predefined macro preserved without evaluation
# define MCC_FILE __FILE__

# macro MCC_REF: identifier reference macro is not emitted directly; only literal macros are currently supported
# define MCC_REF MCC_TARGET

comptime MCC_TARGET = Int32(9)

# macro MCC_NULL: null pointer macro is not emitted directly
# define MCC_NULL ( ( void * ) 0 )

# macro MCC_SIZEOF: unsupported macro replacement list
# define MCC_SIZEOF sizeof ( int )

