# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/macro_comments/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import c_int
from std.sys.info import size_of

# macro MCC_FILE: predefined macro preserved without evaluation
# define MCC_FILE __FILE__

# macro MCC_REF: macro expression references a non-emitted or later macro constant 'MCC_TARGET'
# define MCC_REF MCC_TARGET

comptime MCC_TARGET = c_int(9)

# macro MCC_NULL: null pointer macro is not emitted directly
# define MCC_NULL ( ( void * ) 0 )

comptime MCC_SIZEOF = size_of[c_int]()
