# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/alignment/fixtures/policy_matrix/input.h
# library: policy_matrix  link_name: policy_matrix
# FFI mode: external_call
from std.ffi import external_call, c_char, c_int, c_uchar, c_uint

# struct ag_plain - size=8 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ag_plain(Copyable, Movable, RegisterPassable):
    var tag: c_char
    var value: c_int
# struct ag_alignas_record - size=8 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ag_alignas_record(Copyable, Movable, RegisterPassable):
    var tag: c_char
    var value: c_int
# struct ag_explicit_align - size=16 align=16 (verify packed/aligned ABI)
@align(16)
@fieldwise_init
struct ag_explicit_align(Copyable, Movable):
    var tag: c_char
    var value: c_int
    # synthesized trailing padding: bytes 8..15
    var __pad0: InlineArray[UInt8, 8]
# struct ag_alignas_field - size=64 align=32 (verify packed/aligned ABI)
@align(32)
@fieldwise_init
struct ag_alignas_field(Copyable, Movable):
    var tag: c_char
    # synthesized padding: bytes 4..31
    var __pad0: InlineArray[UInt8, 28]
    var value: c_int
    # synthesized trailing padding: bytes 36..63
    var __pad1: InlineArray[UInt8, 28]
# struct ag_field_align - size=32 align=16 (verify packed/aligned ABI)
@align(16)
@fieldwise_init
struct ag_field_align(Copyable, Movable):
    var tag: c_char
    # synthesized padding: bytes 4..15
    var __pad0: InlineArray[UInt8, 12]
    var value: c_int
    # synthesized trailing padding: bytes 20..31
    var __pad1: InlineArray[UInt8, 12]
# struct ag_packed - size=5 align=1 (verify packed/aligned ABI)
struct ag_packed(Copyable, Movable):
    # exact C field layout for `ag_packed` is not representable as a typed Mojo struct;
    # using opaque byte storage instead.
    # reason: field `size` is at C offset 1, before the typed Mojo offset 4
    var storage: InlineArray[UInt8, 5]
# struct ag_packed_aligned - size=16 align=16 (verify packed/aligned ABI)
@align(16)
struct ag_packed_aligned(Copyable, Movable):
    # exact C field layout for `ag_packed_aligned` is not representable as a typed Mojo struct;
    # using opaque byte storage instead.
    # reason: field `size` is at C offset 1, before the typed Mojo offset 4
    var storage: InlineArray[UInt8, 16]
# struct ag_pragma_packed - size=5 align=1 (verify packed/aligned ABI)
struct ag_pragma_packed(Copyable, Movable):
    # exact C field layout for `ag_pragma_packed` is not representable as a typed Mojo struct;
    # using opaque byte storage instead.
    # reason: field `size` is at C offset 1, before the typed Mojo offset 4
    var storage: InlineArray[UInt8, 5]
# struct ag_pragma_pack2 - size=6 align=2 (verify packed/aligned ABI)
@align(2)
struct ag_pragma_pack2(Copyable, Movable):
    # exact C field layout for `ag_pragma_pack2` is not representable as a typed Mojo struct;
    # using opaque byte storage instead.
    # reason: field `value` is at C offset 2, before the typed Mojo offset 4
    var storage: InlineArray[UInt8, 6]
