# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/alignment/fixtures/policy_matrix/input.h
# library: policy_matrix  link_name: policy_matrix
# FFI mode: external_call

from std.ffi import external_call, c_char, c_int, c_uchar, c_uint

comptime uint8_t = c_uchar

comptime uint32_t = c_uint

@align(4)
@fieldwise_init
struct ag_plain(Copyable, Movable, RegisterPassable):
    var tag: c_char
    var value: c_int

@align(4)
@fieldwise_init
struct ag_alignas_record(Copyable, Movable, RegisterPassable):
    var tag: c_char
    var value: c_int

@align(16)
@fieldwise_init
struct ag_explicit_align(Copyable, Movable):
    var tag: c_char
    var value: c_int
    var __pad0: InlineArray[UInt8, 8]

@align(32)
@fieldwise_init
struct ag_alignas_field(Copyable, Movable):
    var tag: c_char
    var __pad0: InlineArray[UInt8, 28]
    var value: c_int
    var __pad1: InlineArray[UInt8, 28]

@align(16)
@fieldwise_init
struct ag_field_align(Copyable, Movable):
    var tag: c_char
    var __pad0: InlineArray[UInt8, 12]
    var value: c_int
    var __pad1: InlineArray[UInt8, 12]

# NOTE[struct_lowering]: member at byte offset 1 is before the natural typed offset 4; opaque storage emitted
# NOTE[struct_lowering]: C base alignment 1 is smaller than the natural typed Mojo alignment 4; opaque storage emitted
struct ag_packed(Copyable, Movable):
    var storage: InlineArray[UInt8, 5]

# NOTE[struct_lowering]: member at byte offset 1 is before the natural typed offset 4; opaque storage emitted
@align(16)
struct ag_packed_aligned(Copyable, Movable):
    var storage: InlineArray[UInt8, 16]

# NOTE[struct_lowering]: member at byte offset 1 is before the natural typed offset 4; opaque storage emitted
# NOTE[struct_lowering]: C base alignment 1 is smaller than the natural typed Mojo alignment 4; opaque storage emitted
struct ag_pragma_packed(Copyable, Movable):
    var storage: InlineArray[UInt8, 5]

# NOTE[struct_lowering]: member at byte offset 2 is before the natural typed offset 4; opaque storage emitted
# NOTE[struct_lowering]: C base alignment 2 is smaller than the natural typed Mojo alignment 4; opaque storage emitted
@align(2)
struct ag_pragma_pack2(Copyable, Movable):
    var storage: InlineArray[UInt8, 6]
