# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/alignment/fixtures/policy_matrix/input.h
# library: policy_matrix  link_name: policy_matrix
# FFI mode: external_call

from std.ffi import external_call, c_char, c_int

comptime uint8_t = UInt8

comptime uint32_t = UInt32

@align(4)
@fieldwise_init
struct ag_plain(TrivialRegisterPassable):
    var tag: c_char
    var value: c_int

@align(4)
@fieldwise_init
struct ag_alignas_record(TrivialRegisterPassable):
    var tag: c_char
    var value: c_int

@align(16)
@fieldwise_init
struct ag_explicit_align(TrivialRegisterPassable):
    var tag: c_char
    var value: c_int

@align(32)
@fieldwise_init
struct ag_alignas_field(TrivialRegisterPassable):
    var tag: c_char
    var __pad0_0: UInt32
    var __pad0_1: UInt64
    var __pad0_2: UInt64
    var __pad0_3: UInt64
    var value: c_int

@align(16)
@fieldwise_init
struct ag_field_align(TrivialRegisterPassable):
    var tag: c_char
    var __pad0_0: UInt32
    var __pad0_1: UInt64
    var value: c_int

# NOTE[struct_lowering]: member at byte offset 1 is before the natural typed offset 4; opaque storage emitted
# NOTE[struct_lowering]: C base alignment 1 is smaller than the natural typed Mojo alignment 4; opaque storage emitted
struct ag_packed(Copyable, Movable):
    var storage: InlineArray[UInt8, 5]

# NOTE[struct_lowering]: member at byte offset 1 is before the natural typed offset 4; opaque storage emitted
@align(16)
struct ag_packed_aligned(Copyable, Movable):
    var storage: InlineArray[UInt8, 16]

# NOTE[struct_lowering]: member at byte offset 1 is before the natural typed offset 4; opaque storage emitted
# NOTE[struct_lowering]: C base alignment 1 is smaller than the natural typed Mojo alignment 4; opaque storage emitted
struct ag_pragma_packed(Copyable, Movable):
    var storage: InlineArray[UInt8, 5]

# NOTE[struct_lowering]: member at byte offset 2 is before the natural typed offset 4; opaque storage emitted
# NOTE[struct_lowering]: C base alignment 2 is smaller than the natural typed Mojo alignment 4; opaque storage emitted
@align(2)
struct ag_pragma_pack2(Copyable, Movable):
    var storage: InlineArray[UInt8, 6]
