# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/nested_flexible_tail_terminal/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

comptime uint32_t = UInt32

@align(4)
struct nft_packet_tail(Copyable, Movable):
    var len: uint32_t
    var payload: InlineArray[c_uchar, 0]
    @staticmethod
    def payload_offset() -> UInt:
        return 4
    @staticmethod
    def payload_ptr(base: UnsafePointer[nft_packet_tail, ImmutUntrackedOrigin]) -> UnsafePointer[c_uchar, ImmutUntrackedOrigin]:
        var raw = rebind[UnsafePointer[c_uchar, ImmutUntrackedOrigin]](base)
        return raw + 4
    @staticmethod
    def payload_mut_ptr(base: UnsafePointer[nft_packet_tail, MutUntrackedOrigin]) -> UnsafePointer[c_uchar, MutUntrackedOrigin]:
        var raw = rebind[UnsafePointer[c_uchar, MutUntrackedOrigin]](base)
        return raw + 4

@align(4)
struct nft_packet_wrapper(Copyable, Movable):
    var tag: uint32_t
    var tail: nft_packet_tail
    @staticmethod
    def payload_offset() -> UInt:
        return 8
    @staticmethod
    def payload_ptr(base: UnsafePointer[nft_packet_wrapper, ImmutUntrackedOrigin]) -> UnsafePointer[c_uchar, ImmutUntrackedOrigin]:
        var raw = rebind[UnsafePointer[c_uchar, ImmutUntrackedOrigin]](base)
        return raw + 8
    @staticmethod
    def payload_mut_ptr(base: UnsafePointer[nft_packet_wrapper, MutUntrackedOrigin]) -> UnsafePointer[c_uchar, MutUntrackedOrigin]:
        var raw = rebind[UnsafePointer[c_uchar, MutUntrackedOrigin]](base)
        return raw + 8
