# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/scalar_fn_basic/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call
from std.ffi import external_call

def sf_add(a: Int32, b: Int32) abi("C") -> Int32:
    return external_call["sf_add", Int32, Int32, Int32](a, b)

