# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/enum_named_basic/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call, c_uint

comptime enb_mode = c_uint

comptime ENB_ADD = enb_mode(c_uint(1))

comptime ENB_SUB = enb_mode(c_uint(2))

def enb_flip(mode: enb_mode) -> enb_mode:
    return external_call["enb_flip", enb_mode, enb_mode](mode)
