# Generated by mojo_bindgen - do not edit by hand.
# layout tests for: libpng_bindings

from std.sys.info import align_of, size_of
from std.reflection import offset_of
from libpng_bindings import png_color_struct, png_color_16_struct, png_color_8_struct, png_sPLT_entry_struct, png_sPLT_struct, png_text_struct, png_time_struct, png_unknown_chunk_t, png_row_info_struct, png_image


def _check_eq(label: String, got: Int, expected: Int) raises:
    if got != expected:
        raise Error(label + ": got " + String(got) + ", expected " + String(expected))


def test_layout_png_color_struct() raises:
    _check_eq("png_color_struct.size", Int(size_of[png_color_struct]()), 3)
    _check_eq("png_color_struct.align", Int(align_of[png_color_struct]()), 1)
    _check_eq("png_color_struct.red.offset", Int(offset_of[png_color_struct, name="red"]()), 0)
    _check_eq("png_color_struct.green.offset", Int(offset_of[png_color_struct, name="green"]()), 1)
    _check_eq("png_color_struct.blue.offset", Int(offset_of[png_color_struct, name="blue"]()), 2)


def test_layout_png_color_16_struct() raises:
    _check_eq("png_color_16_struct.size", Int(size_of[png_color_16_struct]()), 10)
    _check_eq("png_color_16_struct.align", Int(align_of[png_color_16_struct]()), 2)
    _check_eq("png_color_16_struct.index.offset", Int(offset_of[png_color_16_struct, name="index"]()), 0)
    _check_eq("png_color_16_struct.red.offset", Int(offset_of[png_color_16_struct, name="red"]()), 2)
    _check_eq("png_color_16_struct.green.offset", Int(offset_of[png_color_16_struct, name="green"]()), 4)
    _check_eq("png_color_16_struct.blue.offset", Int(offset_of[png_color_16_struct, name="blue"]()), 6)
    _check_eq("png_color_16_struct.gray.offset", Int(offset_of[png_color_16_struct, name="gray"]()), 8)


def test_layout_png_color_8_struct() raises:
    _check_eq("png_color_8_struct.size", Int(size_of[png_color_8_struct]()), 5)
    _check_eq("png_color_8_struct.align", Int(align_of[png_color_8_struct]()), 1)
    _check_eq("png_color_8_struct.red.offset", Int(offset_of[png_color_8_struct, name="red"]()), 0)
    _check_eq("png_color_8_struct.green.offset", Int(offset_of[png_color_8_struct, name="green"]()), 1)
    _check_eq("png_color_8_struct.blue.offset", Int(offset_of[png_color_8_struct, name="blue"]()), 2)
    _check_eq("png_color_8_struct.gray.offset", Int(offset_of[png_color_8_struct, name="gray"]()), 3)
    _check_eq("png_color_8_struct.alpha.offset", Int(offset_of[png_color_8_struct, name="alpha"]()), 4)


def test_layout_png_sPLT_entry_struct() raises:
    _check_eq("png_sPLT_entry_struct.size", Int(size_of[png_sPLT_entry_struct]()), 10)
    _check_eq("png_sPLT_entry_struct.align", Int(align_of[png_sPLT_entry_struct]()), 2)
    _check_eq("png_sPLT_entry_struct.red.offset", Int(offset_of[png_sPLT_entry_struct, name="red"]()), 0)
    _check_eq("png_sPLT_entry_struct.green.offset", Int(offset_of[png_sPLT_entry_struct, name="green"]()), 2)
    _check_eq("png_sPLT_entry_struct.blue.offset", Int(offset_of[png_sPLT_entry_struct, name="blue"]()), 4)
    _check_eq("png_sPLT_entry_struct.alpha.offset", Int(offset_of[png_sPLT_entry_struct, name="alpha"]()), 6)
    _check_eq("png_sPLT_entry_struct.frequency.offset", Int(offset_of[png_sPLT_entry_struct, name="frequency"]()), 8)


def test_layout_png_sPLT_struct() raises:
    _check_eq("png_sPLT_struct.size", Int(size_of[png_sPLT_struct]()), 32)
    _check_eq("png_sPLT_struct.align", Int(align_of[png_sPLT_struct]()), 8)
    _check_eq("png_sPLT_struct.name.offset", Int(offset_of[png_sPLT_struct, name="name"]()), 0)
    _check_eq("png_sPLT_struct.depth.offset", Int(offset_of[png_sPLT_struct, name="depth"]()), 8)
    _check_eq("png_sPLT_struct.entries.offset", Int(offset_of[png_sPLT_struct, name="entries"]()), 16)
    _check_eq("png_sPLT_struct.nentries.offset", Int(offset_of[png_sPLT_struct, name="nentries"]()), 24)


def test_layout_png_text_struct() raises:
    _check_eq("png_text_struct.size", Int(size_of[png_text_struct]()), 56)
    _check_eq("png_text_struct.align", Int(align_of[png_text_struct]()), 8)
    _check_eq("png_text_struct.compression.offset", Int(offset_of[png_text_struct, name="compression"]()), 0)
    _check_eq("png_text_struct.key.offset", Int(offset_of[png_text_struct, name="key"]()), 8)
    _check_eq("png_text_struct.text.offset", Int(offset_of[png_text_struct, name="text"]()), 16)
    _check_eq("png_text_struct.text_length.offset", Int(offset_of[png_text_struct, name="text_length"]()), 24)
    _check_eq("png_text_struct.itxt_length.offset", Int(offset_of[png_text_struct, name="itxt_length"]()), 32)
    _check_eq("png_text_struct.lang.offset", Int(offset_of[png_text_struct, name="lang"]()), 40)
    _check_eq("png_text_struct.lang_key.offset", Int(offset_of[png_text_struct, name="lang_key"]()), 48)


def test_layout_png_time_struct() raises:
    _check_eq("png_time_struct.size", Int(size_of[png_time_struct]()), 8)
    _check_eq("png_time_struct.align", Int(align_of[png_time_struct]()), 2)
    _check_eq("png_time_struct.year.offset", Int(offset_of[png_time_struct, name="year"]()), 0)
    _check_eq("png_time_struct.month.offset", Int(offset_of[png_time_struct, name="month"]()), 2)
    _check_eq("png_time_struct.day.offset", Int(offset_of[png_time_struct, name="day"]()), 3)
    _check_eq("png_time_struct.hour.offset", Int(offset_of[png_time_struct, name="hour"]()), 4)
    _check_eq("png_time_struct.minute.offset", Int(offset_of[png_time_struct, name="minute"]()), 5)
    _check_eq("png_time_struct.second.offset", Int(offset_of[png_time_struct, name="second"]()), 6)


def test_layout_png_unknown_chunk_t() raises:
    _check_eq("png_unknown_chunk_t.size", Int(size_of[png_unknown_chunk_t]()), 32)
    _check_eq("png_unknown_chunk_t.align", Int(align_of[png_unknown_chunk_t]()), 8)
    _check_eq("png_unknown_chunk_t.name.offset", Int(offset_of[png_unknown_chunk_t, name="name"]()), 0)
    _check_eq("png_unknown_chunk_t.data.offset", Int(offset_of[png_unknown_chunk_t, name="data"]()), 8)
    _check_eq("png_unknown_chunk_t.size.offset", Int(offset_of[png_unknown_chunk_t, name="size"]()), 16)
    _check_eq("png_unknown_chunk_t.location.offset", Int(offset_of[png_unknown_chunk_t, name="location"]()), 24)


def test_layout_png_row_info_struct() raises:
    _check_eq("png_row_info_struct.size", Int(size_of[png_row_info_struct]()), 24)
    _check_eq("png_row_info_struct.align", Int(align_of[png_row_info_struct]()), 8)
    _check_eq("png_row_info_struct.width.offset", Int(offset_of[png_row_info_struct, name="width"]()), 0)
    _check_eq("png_row_info_struct.rowbytes.offset", Int(offset_of[png_row_info_struct, name="rowbytes"]()), 8)
    _check_eq("png_row_info_struct.color_type.offset", Int(offset_of[png_row_info_struct, name="color_type"]()), 16)
    _check_eq("png_row_info_struct.bit_depth.offset", Int(offset_of[png_row_info_struct, name="bit_depth"]()), 17)
    _check_eq("png_row_info_struct.channels.offset", Int(offset_of[png_row_info_struct, name="channels"]()), 18)
    _check_eq("png_row_info_struct.pixel_depth.offset", Int(offset_of[png_row_info_struct, name="pixel_depth"]()), 19)


def test_layout_png_image() raises:
    _check_eq("png_image.size", Int(size_of[png_image]()), 104)
    _check_eq("png_image.align", Int(align_of[png_image]()), 8)
    _check_eq("png_image.opaque.offset", Int(offset_of[png_image, name="opaque"]()), 0)
    _check_eq("png_image.version.offset", Int(offset_of[png_image, name="version"]()), 8)
    _check_eq("png_image.width.offset", Int(offset_of[png_image, name="width"]()), 12)
    _check_eq("png_image.height.offset", Int(offset_of[png_image, name="height"]()), 16)
    _check_eq("png_image.format.offset", Int(offset_of[png_image, name="format"]()), 20)
    _check_eq("png_image.flags.offset", Int(offset_of[png_image, name="flags"]()), 24)
    _check_eq("png_image.colormap_entries.offset", Int(offset_of[png_image, name="colormap_entries"]()), 28)
    _check_eq("png_image.warning_or_error.offset", Int(offset_of[png_image, name="warning_or_error"]()), 32)
    _check_eq("png_image.message.offset", Int(offset_of[png_image, name="message"]()), 36)


def main() raises:
    test_layout_png_color_struct()
    test_layout_png_color_16_struct()
    test_layout_png_color_8_struct()
    test_layout_png_sPLT_entry_struct()
    test_layout_png_sPLT_struct()
    test_layout_png_text_struct()
    test_layout_png_time_struct()
    test_layout_png_unknown_chunk_t()
    test_layout_png_row_info_struct()
    test_layout_png_image()
