# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/variadic_stub/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call

comptime int32_t = Int32

# variadic C function - not callable from thin FFI:
# int32_t vs_sum(count: int32_t, ...)
