# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/variadic_stub/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call
from std.ffi import external_call

# variadic C function - not callable from thin FFI:
# Int32 vs_sum(count: Int32, ...)
