# Generated by mojo_bindgen - do not edit by hand.
# layout tests for: sqlite3_bindings

from std.sys.info import align_of, size_of
from std.reflection import offset_of
from sqlite3_bindings import sqlite3_file, sqlite3_io_methods, sqlite3_vfs, sqlite3_mem_methods, sqlite3_module, sqlite3_index_constraint, sqlite3_index_orderby, sqlite3_index_constraint_usage, sqlite3_index_info, sqlite3_vtab, sqlite3_vtab_cursor, sqlite3_mutex_methods


def _check_eq(label: String, got: Int, expected: Int) raises:
    if got != expected:
        raise Error(label + ": got " + String(got) + ", expected " + String(expected))


def test_layout_sqlite3_file() raises:
    _check_eq("sqlite3_file.size", Int(size_of[sqlite3_file]()), 8)
    _check_eq("sqlite3_file.align", Int(align_of[sqlite3_file]()), 8)
    _check_eq("sqlite3_file.pMethods.offset", Int(offset_of[sqlite3_file, name="pMethods"]()), 0)


def test_layout_sqlite3_io_methods() raises:
    _check_eq("sqlite3_io_methods.size", Int(size_of[sqlite3_io_methods]()), 104)
    _check_eq("sqlite3_io_methods.align", Int(align_of[sqlite3_io_methods]()), 8)
    _check_eq("sqlite3_io_methods.iVersion.offset", Int(offset_of[sqlite3_io_methods, name="iVersion"]()), 0)
    _check_eq("sqlite3_io_methods.xClose.offset", Int(offset_of[sqlite3_io_methods, name="xClose"]()), 8)
    _check_eq("sqlite3_io_methods.xRead.offset", Int(offset_of[sqlite3_io_methods, name="xRead"]()), 16)
    _check_eq("sqlite3_io_methods.xWrite.offset", Int(offset_of[sqlite3_io_methods, name="xWrite"]()), 24)
    _check_eq("sqlite3_io_methods.xTruncate.offset", Int(offset_of[sqlite3_io_methods, name="xTruncate"]()), 32)
    _check_eq("sqlite3_io_methods.xSync.offset", Int(offset_of[sqlite3_io_methods, name="xSync"]()), 40)
    _check_eq("sqlite3_io_methods.xFileSize.offset", Int(offset_of[sqlite3_io_methods, name="xFileSize"]()), 48)
    _check_eq("sqlite3_io_methods.xLock.offset", Int(offset_of[sqlite3_io_methods, name="xLock"]()), 56)
    _check_eq("sqlite3_io_methods.xUnlock.offset", Int(offset_of[sqlite3_io_methods, name="xUnlock"]()), 64)
    _check_eq("sqlite3_io_methods.xCheckReservedLock.offset", Int(offset_of[sqlite3_io_methods, name="xCheckReservedLock"]()), 72)
    _check_eq("sqlite3_io_methods.xFileControl.offset", Int(offset_of[sqlite3_io_methods, name="xFileControl"]()), 80)
    _check_eq("sqlite3_io_methods.xSectorSize.offset", Int(offset_of[sqlite3_io_methods, name="xSectorSize"]()), 88)
    _check_eq("sqlite3_io_methods.xDeviceCharacteristics.offset", Int(offset_of[sqlite3_io_methods, name="xDeviceCharacteristics"]()), 96)


def test_layout_sqlite3_vfs() raises:
    _check_eq("sqlite3_vfs.size", Int(size_of[sqlite3_vfs]()), 136)
    _check_eq("sqlite3_vfs.align", Int(align_of[sqlite3_vfs]()), 8)
    _check_eq("sqlite3_vfs.iVersion.offset", Int(offset_of[sqlite3_vfs, name="iVersion"]()), 0)
    _check_eq("sqlite3_vfs.szOsFile.offset", Int(offset_of[sqlite3_vfs, name="szOsFile"]()), 4)
    _check_eq("sqlite3_vfs.mxPathname.offset", Int(offset_of[sqlite3_vfs, name="mxPathname"]()), 8)
    _check_eq("sqlite3_vfs.pNext.offset", Int(offset_of[sqlite3_vfs, name="pNext"]()), 16)
    _check_eq("sqlite3_vfs.zName.offset", Int(offset_of[sqlite3_vfs, name="zName"]()), 24)
    _check_eq("sqlite3_vfs.pAppData.offset", Int(offset_of[sqlite3_vfs, name="pAppData"]()), 32)
    _check_eq("sqlite3_vfs.xOpen.offset", Int(offset_of[sqlite3_vfs, name="xOpen"]()), 40)
    _check_eq("sqlite3_vfs.xDelete.offset", Int(offset_of[sqlite3_vfs, name="xDelete"]()), 48)
    _check_eq("sqlite3_vfs.xAccess.offset", Int(offset_of[sqlite3_vfs, name="xAccess"]()), 56)
    _check_eq("sqlite3_vfs.xFullPathname.offset", Int(offset_of[sqlite3_vfs, name="xFullPathname"]()), 64)
    _check_eq("sqlite3_vfs.xDlOpen.offset", Int(offset_of[sqlite3_vfs, name="xDlOpen"]()), 72)
    _check_eq("sqlite3_vfs.xDlError.offset", Int(offset_of[sqlite3_vfs, name="xDlError"]()), 80)
    _check_eq("sqlite3_vfs.xDlSym.offset", Int(offset_of[sqlite3_vfs, name="xDlSym"]()), 88)
    _check_eq("sqlite3_vfs.xDlClose.offset", Int(offset_of[sqlite3_vfs, name="xDlClose"]()), 96)
    _check_eq("sqlite3_vfs.xRandomness.offset", Int(offset_of[sqlite3_vfs, name="xRandomness"]()), 104)
    _check_eq("sqlite3_vfs.xSleep.offset", Int(offset_of[sqlite3_vfs, name="xSleep"]()), 112)
    _check_eq("sqlite3_vfs.xCurrentTime.offset", Int(offset_of[sqlite3_vfs, name="xCurrentTime"]()), 120)
    _check_eq("sqlite3_vfs.xGetLastError.offset", Int(offset_of[sqlite3_vfs, name="xGetLastError"]()), 128)


def test_layout_sqlite3_mem_methods() raises:
    _check_eq("sqlite3_mem_methods.size", Int(size_of[sqlite3_mem_methods]()), 64)
    _check_eq("sqlite3_mem_methods.align", Int(align_of[sqlite3_mem_methods]()), 8)
    _check_eq("sqlite3_mem_methods.xMalloc.offset", Int(offset_of[sqlite3_mem_methods, name="xMalloc"]()), 0)
    _check_eq("sqlite3_mem_methods.xFree.offset", Int(offset_of[sqlite3_mem_methods, name="xFree"]()), 8)
    _check_eq("sqlite3_mem_methods.xRealloc.offset", Int(offset_of[sqlite3_mem_methods, name="xRealloc"]()), 16)
    _check_eq("sqlite3_mem_methods.xSize.offset", Int(offset_of[sqlite3_mem_methods, name="xSize"]()), 24)
    _check_eq("sqlite3_mem_methods.xRoundup.offset", Int(offset_of[sqlite3_mem_methods, name="xRoundup"]()), 32)
    _check_eq("sqlite3_mem_methods.xInit.offset", Int(offset_of[sqlite3_mem_methods, name="xInit"]()), 40)
    _check_eq("sqlite3_mem_methods.xShutdown.offset", Int(offset_of[sqlite3_mem_methods, name="xShutdown"]()), 48)
    _check_eq("sqlite3_mem_methods.pAppData.offset", Int(offset_of[sqlite3_mem_methods, name="pAppData"]()), 56)


def test_layout_sqlite3_module() raises:
    _check_eq("sqlite3_module.size", Int(size_of[sqlite3_module]()), 160)
    _check_eq("sqlite3_module.align", Int(align_of[sqlite3_module]()), 8)
    _check_eq("sqlite3_module.iVersion.offset", Int(offset_of[sqlite3_module, name="iVersion"]()), 0)
    _check_eq("sqlite3_module.xCreate.offset", Int(offset_of[sqlite3_module, name="xCreate"]()), 8)
    _check_eq("sqlite3_module.xConnect.offset", Int(offset_of[sqlite3_module, name="xConnect"]()), 16)
    _check_eq("sqlite3_module.xBestIndex.offset", Int(offset_of[sqlite3_module, name="xBestIndex"]()), 24)
    _check_eq("sqlite3_module.xDisconnect.offset", Int(offset_of[sqlite3_module, name="xDisconnect"]()), 32)
    _check_eq("sqlite3_module.xDestroy.offset", Int(offset_of[sqlite3_module, name="xDestroy"]()), 40)
    _check_eq("sqlite3_module.xOpen.offset", Int(offset_of[sqlite3_module, name="xOpen"]()), 48)
    _check_eq("sqlite3_module.xClose.offset", Int(offset_of[sqlite3_module, name="xClose"]()), 56)
    _check_eq("sqlite3_module.xFilter.offset", Int(offset_of[sqlite3_module, name="xFilter"]()), 64)
    _check_eq("sqlite3_module.xNext.offset", Int(offset_of[sqlite3_module, name="xNext"]()), 72)
    _check_eq("sqlite3_module.xEof.offset", Int(offset_of[sqlite3_module, name="xEof"]()), 80)
    _check_eq("sqlite3_module.xColumn.offset", Int(offset_of[sqlite3_module, name="xColumn"]()), 88)
    _check_eq("sqlite3_module.xRowid.offset", Int(offset_of[sqlite3_module, name="xRowid"]()), 96)
    _check_eq("sqlite3_module.xUpdate.offset", Int(offset_of[sqlite3_module, name="xUpdate"]()), 104)
    _check_eq("sqlite3_module.xBegin.offset", Int(offset_of[sqlite3_module, name="xBegin"]()), 112)
    _check_eq("sqlite3_module.xSync.offset", Int(offset_of[sqlite3_module, name="xSync"]()), 120)
    _check_eq("sqlite3_module.xCommit.offset", Int(offset_of[sqlite3_module, name="xCommit"]()), 128)
    _check_eq("sqlite3_module.xRollback.offset", Int(offset_of[sqlite3_module, name="xRollback"]()), 136)
    _check_eq("sqlite3_module.xFindFunction.offset", Int(offset_of[sqlite3_module, name="xFindFunction"]()), 144)
    _check_eq("sqlite3_module.xRename.offset", Int(offset_of[sqlite3_module, name="xRename"]()), 152)


def test_layout_sqlite3_index_constraint() raises:
    _check_eq("sqlite3_index_constraint.size", Int(size_of[sqlite3_index_constraint]()), 12)
    _check_eq("sqlite3_index_constraint.align", Int(align_of[sqlite3_index_constraint]()), 4)
    _check_eq("sqlite3_index_constraint.iColumn.offset", Int(offset_of[sqlite3_index_constraint, name="iColumn"]()), 0)
    _check_eq("sqlite3_index_constraint.op.offset", Int(offset_of[sqlite3_index_constraint, name="op"]()), 4)
    _check_eq("sqlite3_index_constraint.usable.offset", Int(offset_of[sqlite3_index_constraint, name="usable"]()), 5)
    _check_eq("sqlite3_index_constraint.iTermOffset.offset", Int(offset_of[sqlite3_index_constraint, name="iTermOffset"]()), 8)


def test_layout_sqlite3_index_orderby() raises:
    _check_eq("sqlite3_index_orderby.size", Int(size_of[sqlite3_index_orderby]()), 8)
    _check_eq("sqlite3_index_orderby.align", Int(align_of[sqlite3_index_orderby]()), 4)
    _check_eq("sqlite3_index_orderby.iColumn.offset", Int(offset_of[sqlite3_index_orderby, name="iColumn"]()), 0)
    _check_eq("sqlite3_index_orderby.desc.offset", Int(offset_of[sqlite3_index_orderby, name="desc"]()), 4)


def test_layout_sqlite3_index_constraint_usage() raises:
    _check_eq("sqlite3_index_constraint_usage.size", Int(size_of[sqlite3_index_constraint_usage]()), 8)
    _check_eq("sqlite3_index_constraint_usage.align", Int(align_of[sqlite3_index_constraint_usage]()), 4)
    _check_eq("sqlite3_index_constraint_usage.argvIndex.offset", Int(offset_of[sqlite3_index_constraint_usage, name="argvIndex"]()), 0)
    _check_eq("sqlite3_index_constraint_usage.omit.offset", Int(offset_of[sqlite3_index_constraint_usage, name="omit"]()), 4)


def test_layout_sqlite3_index_info() raises:
    _check_eq("sqlite3_index_info.size", Int(size_of[sqlite3_index_info]()), 72)
    _check_eq("sqlite3_index_info.align", Int(align_of[sqlite3_index_info]()), 8)
    _check_eq("sqlite3_index_info.nConstraint.offset", Int(offset_of[sqlite3_index_info, name="nConstraint"]()), 0)
    _check_eq("sqlite3_index_info.aConstraint.offset", Int(offset_of[sqlite3_index_info, name="aConstraint"]()), 8)
    _check_eq("sqlite3_index_info.nOrderBy.offset", Int(offset_of[sqlite3_index_info, name="nOrderBy"]()), 16)
    _check_eq("sqlite3_index_info.aOrderBy.offset", Int(offset_of[sqlite3_index_info, name="aOrderBy"]()), 24)
    _check_eq("sqlite3_index_info.aConstraintUsage.offset", Int(offset_of[sqlite3_index_info, name="aConstraintUsage"]()), 32)
    _check_eq("sqlite3_index_info.idxNum.offset", Int(offset_of[sqlite3_index_info, name="idxNum"]()), 40)
    _check_eq("sqlite3_index_info.idxStr.offset", Int(offset_of[sqlite3_index_info, name="idxStr"]()), 48)
    _check_eq("sqlite3_index_info.needToFreeIdxStr.offset", Int(offset_of[sqlite3_index_info, name="needToFreeIdxStr"]()), 56)
    _check_eq("sqlite3_index_info.orderByConsumed.offset", Int(offset_of[sqlite3_index_info, name="orderByConsumed"]()), 60)
    _check_eq("sqlite3_index_info.estimatedCost.offset", Int(offset_of[sqlite3_index_info, name="estimatedCost"]()), 64)


def test_layout_sqlite3_vtab() raises:
    _check_eq("sqlite3_vtab.size", Int(size_of[sqlite3_vtab]()), 24)
    _check_eq("sqlite3_vtab.align", Int(align_of[sqlite3_vtab]()), 8)
    _check_eq("sqlite3_vtab.pModule.offset", Int(offset_of[sqlite3_vtab, name="pModule"]()), 0)
    _check_eq("sqlite3_vtab.nRef.offset", Int(offset_of[sqlite3_vtab, name="nRef"]()), 8)
    _check_eq("sqlite3_vtab.zErrMsg.offset", Int(offset_of[sqlite3_vtab, name="zErrMsg"]()), 16)


def test_layout_sqlite3_vtab_cursor() raises:
    _check_eq("sqlite3_vtab_cursor.size", Int(size_of[sqlite3_vtab_cursor]()), 8)
    _check_eq("sqlite3_vtab_cursor.align", Int(align_of[sqlite3_vtab_cursor]()), 8)
    _check_eq("sqlite3_vtab_cursor.pVtab.offset", Int(offset_of[sqlite3_vtab_cursor, name="pVtab"]()), 0)


def test_layout_sqlite3_mutex_methods() raises:
    _check_eq("sqlite3_mutex_methods.size", Int(size_of[sqlite3_mutex_methods]()), 72)
    _check_eq("sqlite3_mutex_methods.align", Int(align_of[sqlite3_mutex_methods]()), 8)
    _check_eq("sqlite3_mutex_methods.xMutexInit.offset", Int(offset_of[sqlite3_mutex_methods, name="xMutexInit"]()), 0)
    _check_eq("sqlite3_mutex_methods.xMutexEnd.offset", Int(offset_of[sqlite3_mutex_methods, name="xMutexEnd"]()), 8)
    _check_eq("sqlite3_mutex_methods.xMutexAlloc.offset", Int(offset_of[sqlite3_mutex_methods, name="xMutexAlloc"]()), 16)
    _check_eq("sqlite3_mutex_methods.xMutexFree.offset", Int(offset_of[sqlite3_mutex_methods, name="xMutexFree"]()), 24)
    _check_eq("sqlite3_mutex_methods.xMutexEnter.offset", Int(offset_of[sqlite3_mutex_methods, name="xMutexEnter"]()), 32)
    _check_eq("sqlite3_mutex_methods.xMutexTry.offset", Int(offset_of[sqlite3_mutex_methods, name="xMutexTry"]()), 40)
    _check_eq("sqlite3_mutex_methods.xMutexLeave.offset", Int(offset_of[sqlite3_mutex_methods, name="xMutexLeave"]()), 48)
    _check_eq("sqlite3_mutex_methods.xMutexHeld.offset", Int(offset_of[sqlite3_mutex_methods, name="xMutexHeld"]()), 56)
    _check_eq("sqlite3_mutex_methods.xMutexNotheld.offset", Int(offset_of[sqlite3_mutex_methods, name="xMutexNotheld"]()), 64)


def main() raises:
    test_layout_sqlite3_file()
    test_layout_sqlite3_io_methods()
    test_layout_sqlite3_vfs()
    test_layout_sqlite3_mem_methods()
    test_layout_sqlite3_module()
    test_layout_sqlite3_index_constraint()
    test_layout_sqlite3_index_orderby()
    test_layout_sqlite3_index_constraint_usage()
    test_layout_sqlite3_index_info()
    test_layout_sqlite3_vtab()
    test_layout_sqlite3_vtab_cursor()
    test_layout_sqlite3_mutex_methods()
