# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/non_register_return_stub/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call
from std.ffi import external_call

# struct nrr_payload - size=8 align=4 (verify packed/aligned ABI)
@fieldwise_init
struct nrr_payload(Copyable, Movable):
    var values: InlineArray[Int32, 2]
# C return type is not RegisterPassable - external_call cannot model this return; bind manually.
# nrr_payload nrr_build()

