# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/opaque_forward_ptrs/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call

struct ofp_handle(Copyable, Movable):
    pass

def ofp_open() abi("C") -> UnsafePointer[ofp_handle, MutExternalOrigin]:
    return external_call["ofp_open", UnsafePointer[ofp_handle, MutExternalOrigin]]()

def ofp_close(handle: UnsafePointer[ofp_handle, MutExternalOrigin]) abi("C") -> None:
    external_call["ofp_close", NoneType, UnsafePointer[ofp_handle, MutExternalOrigin]](handle)
