# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/globals_and_consts/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call
from std.ffi import external_call

comptime DEFAULT_LIMIT = UInt32(42)

# struct point - size=8 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct point(Copyable, Movable, RegisterPassable):
    var x: Int32
    var y: Int32
# global variable global_counter: Int32 (manual binding required)

