# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/globals_and_consts/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call, DEFAULT_RTLD, OwnedDLHandle, c_int, c_uint

# Resolve symbols from libraries already linked into this process.
def _bindgen_dl() raises -> OwnedDLHandle:
    return OwnedDLHandle(DEFAULT_RTLD)

struct GlobalVar[T: Copyable & ImplicitlyDestructible, //, link: StaticString]:
    @staticmethod
    def _raw() raises -> UnsafePointer[Self.T, MutAnyOrigin]:
        var opt: Optional[UnsafePointer[Self.T, MutAnyOrigin]] = _bindgen_dl().get_symbol[Self.T](StringSlice(Self.link))
        if not opt:
            raise Error(String("bindgen: missing C global symbol"))
        return opt.value()

    @staticmethod
    def ptr() raises -> UnsafePointer[Self.T, MutExternalOrigin]:
        return rebind[UnsafePointer[Self.T, MutExternalOrigin]](Self._raw())

    @staticmethod
    def load() raises -> Self.T:
        return Self._raw()[].copy()

    @staticmethod
    def store(value: Self.T) raises -> None:
        var p = rebind[UnsafePointer[Self.T, MutExternalOrigin]](Self._raw())
        p[] = value.copy()

struct GlobalConst[T: Copyable & ImplicitlyDestructible, //, link: StaticString]:
    @staticmethod
    def _raw() raises -> UnsafePointer[Self.T, MutAnyOrigin]:
        var opt: Optional[UnsafePointer[Self.T, MutAnyOrigin]] = _bindgen_dl().get_symbol[Self.T](StringSlice(Self.link))
        if not opt:
            raise Error(String("bindgen: missing C global symbol"))
        return opt.value()

    @staticmethod
    def ptr() raises -> UnsafePointer[Self.T, ImmutExternalOrigin]:
        return rebind[UnsafePointer[Self.T, ImmutExternalOrigin]](Self._raw())

    @staticmethod
    def load() raises -> Self.T:
        return Self._raw()[].copy()

comptime DEFAULT_LIMIT = c_uint(42)

@align(4)
@fieldwise_init
struct point(Copyable, Movable, RegisterPassable):
    var x: c_int
    var y: c_int

# global `global_counter` -> c_int
comptime global_counter = GlobalVar[T=c_int, link="global_counter"]
