# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/typedef_chain/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call
from std.ffi import external_call, c_uint

comptime tc_word = c_uint

comptime tc_word_alias = tc_word

def tc_identity(value: tc_word_alias) abi("C") -> tc_word_alias:
    return external_call["tc_identity", c_uint, tc_word_alias](value)

