# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/struct_plain_fields/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call, c_int

comptime int32_t = c_int

@align(4)
@fieldwise_init
struct spf_pair(TrivialRegisterPassable):
    var lhs: int32_t
    var rhs: int32_t
