# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/struct_plain_fields/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call
from std.ffi import external_call

# struct spf_pair - size=8 align=4 (verify packed/aligned ABI)
@fieldwise_init
struct spf_pair(Copyable, Movable, RegisterPassable):
    var lhs: Int32
    var rhs: Int32
