# Generated by mojo_bindgen - do not edit by hand.
# source: /home/mohamed/Documents/Projects/mojo_bindgen/tests/fixtures/everything.h
# library: everything  link_name: everything
# FFI mode: external_call
from std.ffi import external_call
from std.memory import ImmutOpaquePointer, MutOpaquePointer

# -- C union `ev_any_watcher` - not emitted as a struct.
# By-value uses InlineArray[UInt8, 48] unless you wrap a manual UnsafeUnion (unique trivial members).
# C size=48 bytes, align=8.
# Members (reference only):
#   io: ev_io
#   stat: ev_stat
# struct ev_tstamp_pair - size=16 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_tstamp_pair(Copyable, Movable, RegisterPassable):
    var at: Float64
    var repeat: Float64
# struct ev_io - size=24 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_io(Copyable, Movable, RegisterPassable):
    var active: Int32
    var pending: Int32
    var data: MutOpaquePointer[MutExternalOrigin]
    var fd: Int32
    var events: Int32
# struct ev_flags - size=4 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_flags(Copyable, Movable, RegisterPassable):
    # bitfield: C bits 0..0 (1 bits) on unsigned int
    # ABI: verify bitfield layout matches target C compiler.
    var active: UInt32
    # bitfield: C bits 1..1 (1 bits) on unsigned int
    # ABI: verify bitfield layout matches target C compiler.
    var pending: UInt32
    # bitfield: C bits 2..5 (4 bits) on unsigned int
    # ABI: verify bitfield layout matches target C compiler.
    var priority: UInt32
    # bitfield: C bits 6..9 (4 bits) on unsigned int
    # ABI: verify bitfield layout matches target C compiler.
    var backend: UInt32
    # bitfield: C bits 0..21 (22 bits) on unsigned int
    # ABI: verify bitfield layout matches target C compiler.
    var _anon_4: UInt32
# struct ev_prepare_batch - size=136 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_prepare_batch(Copyable, Movable):
    var watchers: InlineArray[MutOpaquePointer[MutExternalOrigin], 16]
    var count: Int32
    var id: InlineArray[UInt8, 4]
# struct ev_watcher_list - size=24 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_watcher_list(Copyable, Movable, RegisterPassable):
    var next: UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin]
    # function pointer (fixed): (NoneType, UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin])
    var cb: MutOpaquePointer[MutExternalOrigin]
    var data: MutOpaquePointer[MutExternalOrigin]
# struct ev_packet - size=8 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_packet(Copyable, Movable, RegisterPassable):
    var length: Int32
    var type: Int32
    var payload: UnsafePointer[UInt8, MutExternalOrigin]
# struct ev_packed_header - size=5 align=1 (verify packed/aligned ABI)
@fieldwise_init
struct ev_packed_header(Copyable, Movable, RegisterPassable):
    var flag: UInt8
    var length: UInt32
# struct ev_aligned_data - size=32 align=16 (verify packed/aligned ABI)
@align(16)
@fieldwise_init
struct ev_aligned_data(Copyable, Movable, RegisterPassable):
    var a: Int8
    var b: Int32
# struct ev_matrix - size=64 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_matrix(Copyable, Movable):
    var transform: InlineArray[InlineArray[Float32, 4], 4]
# struct ev_node - size=16 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_node(Copyable, Movable):
    var next: UnsafePointer[ev_node, MutExternalOrigin]
    var prev: UnsafePointer[ev_node, MutExternalOrigin]
# struct ev_a - size=8 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_a(Copyable, Movable):
    var next: UnsafePointer[ev_a, MutExternalOrigin]
# struct ev_bf - size=4 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_bf(Copyable, Movable, RegisterPassable):
    # bitfield: C bits 0..2 (3 bits) on unsigned char
    # ABI: verify bitfield layout matches target C compiler.
    var a: UInt8
    # bitfield: C bits 3..7 (5 bits) on int
    # ABI: verify bitfield layout matches target C compiler.
    var b: Int32
    # bitfield: C bits 8..8 (1 bits) on _Bool
    # ABI: verify bitfield layout matches target C compiler.
    var c: Bool
# struct ev_bf2 - size=8 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_bf2(Copyable, Movable, RegisterPassable):
    # bitfield: C bits 0..19 (20 bits) on unsigned int
    # ABI: verify bitfield layout matches target C compiler.
    var a: UInt32
    # bitfield: C bits 32..51 (20 bits) on unsigned int
    # ABI: verify bitfield layout matches target C compiler.
    var b: UInt32
# struct ev_bf3 - size=8 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_bf3(Copyable, Movable, RegisterPassable):
    # bitfield: C bits 0..0 (1 bits) on unsigned int
    # ABI: verify bitfield layout matches target C compiler.
    var a: UInt32
    # bitfield: C bits 0..-1 (0 bits) on unsigned int
    # ABI: verify bitfield layout matches target C compiler.
    var _anon_1: UInt32
    # bitfield: C bits 32..32 (1 bits) on unsigned int
    # ABI: verify bitfield layout matches target C compiler.
    var b: UInt32
# struct ev_pad - size=12 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_pad(Copyable, Movable, RegisterPassable):
    var a: Int8
    var b: Int32
    var c: Int8
# struct ev_event - size=16 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_event(Copyable, Movable, RegisterPassable):
    var type: Int32
# struct ev_stat - size=48 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_stat(Copyable, Movable, RegisterPassable):
    var prev: ev_tstamp_pair
    var curr: ev_tstamp_pair
    var path: UnsafePointer[Int8, ImmutExternalOrigin]
    var interval: UInt32
# enum ev_backend - underlying unsigned int -> UInt32 (verify C ABI)
@fieldwise_init
struct ev_backend(Copyable, Movable, RegisterPassable):
    var value: UInt32
    comptime EVBACKEND_SELECT = Self(UInt32(1))
    comptime EVBACKEND_POLL = Self(UInt32(2))
    comptime EVBACKEND_EPOLL = Self(UInt32(4))
    comptime EVBACKEND_KQUEUE = Self(UInt32(8))
    comptime EVBACKEND_DEVPOLL = Self(UInt32(16))
    comptime EVBACKEND_PORT = Self(UInt32(32))
    comptime EVBACKEND_MASK = Self(UInt32(65535))
    comptime EVBACKEND_COUNT = Self(UInt32(6))
# enum ev_run_flags - underlying unsigned int -> UInt32 (verify C ABI)
@fieldwise_init
struct ev_run_flags(Copyable, Movable, RegisterPassable):
    var value: UInt32
    comptime EVRUN_NOWAIT = Self(UInt32(1))
    comptime EVRUN_ONCE = Self(UInt32(2))
# enum enum (unnamed at /home/mohamed/Documents/Projects/mojo_bindgen/tests/fixtures/everything.h:55:1) - underlying int -> Int32 (verify C ABI)
@fieldwise_init
struct enum__unnamed_at__home_mohamed_Documents_Projects_mojo_bindgen_tests_fixtures_everything_h_55_1_(Copyable, Movable, RegisterPassable):
    var value: Int32
    comptime EV_UNDEF = Self(Int32(-1))
    comptime EV_NONE = Self(Int32(0))
    comptime EV_READ = Self(Int32(1))
    comptime EV_WRITE = Self(Int32(2))
    comptime EV_TIMER = Self(Int32(256))
comptime ev_any_watcher = InlineArray[UInt8, 48]

comptime ev_tstamp = Float64

comptime ev_time_t = Float64

comptime ev_eventmask = UInt32

comptime ev_loop_ptr = UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin]

comptime ev_cb_t = MutOpaquePointer[MutExternalOrigin]

def ev_version_major() abi("C") -> UInt32:
    return external_call["ev_version_major", UInt32]()

def ev_loop_new(flags: UInt32) abi("C") -> UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin]:
    return external_call["ev_loop_new", UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin], UInt32](flags)

def ev_io_init(w: UnsafePointer[ev_io, MutExternalOrigin], cb: ev_cb_t, fd: Int32, events: Int32) abi("C") -> None:
    external_call["ev_io_init", NoneType, UnsafePointer[ev_io, MutExternalOrigin], MutOpaquePointer[MutExternalOrigin], Int32, Int32](w, cb, fd, events)

def ev_stat_path_watch(w: UnsafePointer[ev_stat, ImmutExternalOrigin], path: UnsafePointer[Int8, ImmutExternalOrigin]) abi("C") -> Int32:
    return external_call["ev_stat_path_watch", Int32, UnsafePointer[ev_stat, ImmutExternalOrigin], UnsafePointer[Int8, ImmutExternalOrigin]](w, path)

def ev_now_pair(loop: UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin]) abi("C") -> ev_tstamp_pair:
    return external_call["ev_now_pair", ev_tstamp_pair, UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin]](loop)

# variadic C function - not callable from thin FFI:
# NoneType ev_set_userdata(loop: UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin], data: MutOpaquePointer[MutExternalOrigin], ...)
def ev_feed_event_batch(loop: UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin], events: UnsafePointer[Int32, MutExternalOrigin], count: Int32) abi("C") -> None:
    external_call["ev_feed_event_batch", NoneType, UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin], UnsafePointer[Int32, MutExternalOrigin], Int32](loop, events, count)

def ev_get_version_string(out_version: UnsafePointer[UnsafePointer[Int8, MutExternalOrigin], MutExternalOrigin]) abi("C") -> None:
    external_call["ev_get_version_string", NoneType, UnsafePointer[UnsafePointer[Int8, MutExternalOrigin], MutExternalOrigin]](out_version)

def ev_process_argv(argc: Int32, argv: UnsafePointer[UnsafePointer[UnsafePointer[Int8, MutExternalOrigin], MutExternalOrigin], MutExternalOrigin]) abi("C") -> Int32:
    return external_call["ev_process_argv", Int32, Int32, UnsafePointer[UnsafePointer[UnsafePointer[Int8, MutExternalOrigin], MutExternalOrigin], MutExternalOrigin]](argc, argv)

# global variable ev_global_error_code: Int32 (manual binding required)

# global variable ev_backend_name: UnsafePointer[Int8, ImmutExternalOrigin] (manual binding required)

def ev_is_active(loop: UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin]) abi("C") -> Bool:
    return external_call["ev_is_active", Bool, UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin]](loop)

def ev_fast_check(x: Int32) abi("C") -> Int32:
    return external_call["ev_fast_check", Int32, Int32](x)

def ev_atomic_add(counter: UnsafePointer[Int32, MutExternalOrigin], amount: Int32) abi("C") -> None:
    external_call["ev_atomic_add", NoneType, UnsafePointer[Int32, MutExternalOrigin], Int32](counter, amount)

def ev_memory_copy(dest: MutOpaquePointer[MutExternalOrigin], src: ImmutOpaquePointer[ImmutExternalOrigin], n: UInt64) abi("C") -> None:
    external_call["ev_memory_copy", NoneType, MutOpaquePointer[MutExternalOrigin], ImmutOpaquePointer[ImmutExternalOrigin], UInt64](dest, src, n)

# enum ev_big - underlying unsigned long -> UInt64 (verify C ABI)
@fieldwise_init
struct ev_big(Copyable, Movable, RegisterPassable):
    var value: UInt64
    comptime EV_BIG = Self(UInt64(9223372036854775807))
# global variable ev_ptr_to_array: UnsafePointer[InlineArray[Int32, 10], MutExternalOrigin] (manual binding required)

# global variable ev_array_of_ptrs: InlineArray[UnsafePointer[Int32, MutExternalOrigin], 10] (manual binding required)

def ev_legacy(a: Int32, b: Float64) abi("C") -> Int32:
    return external_call["ev_legacy", Int32, Int32, Float64](a, b)

def ev_inline(x: Int32) abi("C") -> Int32:
    return external_call["ev_inline", Int32, Int32](x)

def ev_extern_inline(x: Int32) abi("C") -> Int32:
    return external_call["ev_extern_inline", Int32, Int32](x)

comptime ev_dynamic_t = Int32

# global variable ev_internal_state: Int32 (manual binding required)

# global variable ev_default_loop: UnsafePointer[MutOpaquePointer[MutExternalOrigin], ImmutExternalOrigin] (manual binding required)

comptime EV_VERSION_MAJOR = Int32(4)

comptime EV_VERSION_MINOR = Int32(33)

comptime EV_MAXPRI = Int32(9)

comptime EV_FLAG_AUTO = UInt32(1)

comptime EV_FLAG_DYNAMIC = UInt32(2)

comptime EV_FLAG_MASK = UInt32(65535)

comptime EV_LABEL = "libev"

comptime EV_TYPE = int

