# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/global_stub_const_ptr/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call, OwnedDLHandle, _Global
from std.memory.unsafe_pointer import unsafe_cast
from std.pathlib import Path

struct _BindgenApi(Movable):
    var _lib: OwnedDLHandle
    var _loaded: Bool

    def __init__(out self):
        self._lib = OwnedDLHandle(unsafe_uninitialized=True)
        self._loaded = False

    def _ensure_loaded(mut self) raises:
        if not self._loaded:
            self._lib = OwnedDLHandle()
            self._loaded = True

    def get_symbol[
        T: AnyType,
        symbol: StaticString,
    ](mut self) raises -> UnsafePointer[T, MutUntrackedOrigin]:
        self._ensure_loaded()
        var opt = self._lib.get_symbol[T](StringSlice(symbol))
        if not opt:
            raise Error(String("bindgen: missing C symbol: ") + String(symbol))
        return opt.value()

    def get_function[
        symbol: StaticString,
        F: TrivialRegisterPassable,
    ](mut self) raises -> F:
        self._ensure_loaded()
        var opt = self._lib.get_symbol[NoneType](StringSlice(symbol))
        if not opt:
            raise Error(String("bindgen: missing C function symbol: ") + String(symbol))
        return UnsafePointer(to=opt.value()).bitcast[F]()[]

def _bindgen_init_api() -> _BindgenApi:
    return _BindgenApi()

comptime _BINDGEN_API = _Global[
    _BindgenApi,
    "mojo_bindgen/surface_globals/api",
    _bindgen_init_api,
]

@always_inline
def _bindgen_api() -> UnsafePointer[_BindgenApi, MutUntrackedOrigin]:
    return _BINDGEN_API.get_or_create_ptr()

struct GlobalVar[T: Copyable & ImplicitlyDestructible, //, link: StaticString]:
    @staticmethod
    def _raw() raises -> UnsafePointer[Self.T, MutAnyOrigin]:
        return _bindgen_api()[].get_symbol[Self.T, Self.link]()

    @staticmethod
    def ptr() raises -> UnsafePointer[Self.T, MutExternalOrigin]:
        return rebind[UnsafePointer[Self.T, MutExternalOrigin]](Self._raw())

    @staticmethod
    def load() raises -> Self.T:
        return Self._raw()[].copy()

    @staticmethod
    def store(value: Self.T) raises -> None:
        var p = rebind[UnsafePointer[Self.T, MutExternalOrigin]](Self._raw())
        p[] = value.copy()

struct GlobalConst[T: Copyable & ImplicitlyDestructible, //, link: StaticString]:
    @staticmethod
    def _raw() raises -> UnsafePointer[Self.T, MutAnyOrigin]:
        return _bindgen_api()[].get_symbol[Self.T, Self.link]()

    @staticmethod
    def ptr() raises -> UnsafePointer[Self.T, ImmutExternalOrigin]:
        return rebind[UnsafePointer[Self.T, ImmutExternalOrigin]](Self._raw())

    @staticmethod
    def load() raises -> Self.T:
        return Self._raw()[].copy()

struct gscp_cfg(Copyable, Movable):
    pass

# global `gscp_default_cfg` -> Optional[UnsafePointer[gscp_cfg, ImmutExternalOrigin]]
comptime gscp_default_cfg = GlobalVar[T=Optional[UnsafePointer[gscp_cfg, ImmutExternalOrigin]], link="gscp_default_cfg"]
