# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/global_stub_const_ptr/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call
from std.ffi import external_call
from std.memory import ImmutOpaquePointer, MutOpaquePointer

# global variable gscp_default_cfg: UnsafePointer[MutOpaquePointer[MutExternalOrigin], ImmutExternalOrigin] (manual binding required)

