"""Render Mojo sidecars that validate emitted record layout."""

from __future__ import annotations

from dataclasses import dataclass

from mojo_bindgen.analysis.lowering_support import field_mojo_name, record_by_decl_id, record_name
from mojo_bindgen.analysis.record_layout import analyze_record_layout
from mojo_bindgen.ir import (
    BitfieldGroupMember,
    MojoModule,
    OpaqueStorageMember,
    PaddingMember,
    StoredMember,
    Struct,
    StructDecl,
    StructKind,
    Unit,
)


@dataclass(frozen=True)
class LayoutCheck:
    label: str
    expression: str
    expected: int


@dataclass(frozen=True)
class LayoutRecordCheck:
    record_name: str
    checks: tuple[LayoutCheck, ...]


def collect_layout_record_checks(
    *,
    normalized_unit: Unit,
    mojo_module: MojoModule,
) -> tuple[LayoutRecordCheck, ...]:
    """Collect C-layout expectations for records that have emitted Mojo structs."""

    mojo_structs = {decl.name: decl for decl in mojo_module.decls if isinstance(decl, StructDecl)}
    record_map = record_by_decl_id(normalized_unit)
    checks: list[LayoutRecordCheck] = []

    for decl in normalized_unit.decls:
        if not isinstance(decl, Struct):
            continue
        record_check = _layout_record_check(decl, normalized_unit, mojo_structs, record_map)
        if record_check is not None:
            checks.append(record_check)
    return tuple(checks)


def _layout_record_check(
    decl: Struct,
    unit: Unit,
    mojo_structs: dict[str, StructDecl],
    record_map: dict[str, Struct],
) -> LayoutRecordCheck | None:
    if decl.is_union or not decl.is_complete:
        return None

    mojo_name = record_name(decl)
    mojo_decl = mojo_structs.get(mojo_name)
    if mojo_decl is None or mojo_decl.kind != StructKind.PLAIN:
        return None

    facts = analyze_record_layout(
        decl,
        target_abi=unit.target_abi,
        record_map=record_map,
    )
    if not facts.is_complete:
        return None

    checks = [
        LayoutCheck(
            label=f"{mojo_name}.size",
            expression=f"size_of[{mojo_name}]()",
            expected=facts.size_bytes,
        ),
    ]
    if facts.align_bytes is not None:
        checks.append(
            LayoutCheck(
                label=f"{mojo_name}.align",
                expression=f"align_of[{mojo_name}]()",
                expected=facts.align_bytes,
            )
        )

    if _is_opaque_storage_decl(mojo_decl):
        return LayoutRecordCheck(record_name=mojo_name, checks=tuple(checks))

    member_indices = _member_indices(mojo_decl)
    for field_fact in facts.plain_fields:
        field = decl.fields[field_fact.index]
        member_name = field_mojo_name(field, field_fact.index)
        mojo_index = member_indices.get(member_name)
        if mojo_index is None:
            continue
        checks.append(
            LayoutCheck(
                label=f"{mojo_name}.{member_name}.offset",
                expression=f"r.field_offset[index={mojo_index}]()",
                expected=field_fact.byte_offset,
            )
        )

    for run in facts.bitfield_runs:
        mojo_index = member_indices.get(run.name)
        if mojo_index is None:
            continue
        checks.append(
            LayoutCheck(
                label=f"{mojo_name}.{run.name}.offset",
                expression=f"r.field_offset[index={mojo_index}]()",
                expected=run.byte_offset,
            )
        )

    return LayoutRecordCheck(record_name=mojo_name, checks=tuple(checks))


def _is_opaque_storage_decl(decl: StructDecl) -> bool:
    return len(decl.members) == 1 and isinstance(decl.members[0], OpaqueStorageMember)


def _member_indices(decl: StructDecl) -> dict[str, int]:
    indices: dict[str, int] = {}
    for index, member in enumerate(decl.members):
        if isinstance(member, StoredMember):
            indices[member.name] = index
        elif isinstance(member, BitfieldGroupMember):
            indices[member.storage_name] = index
        elif isinstance(member, OpaqueStorageMember):
            indices[member.name] = index
        elif isinstance(member, PaddingMember):
            indices[member.name] = index
    return indices


def render_layout_test_module(
    *,
    normalized_unit: Unit,
    mojo_module: MojoModule,
    main_module_name: str,
) -> str:
    """Render a standalone Mojo file that asks Mojo for emitted record layout."""

    checks = collect_layout_record_checks(
        normalized_unit=normalized_unit,
        mojo_module=mojo_module,
    )
    lines = [
        "# Generated by mojo_bindgen - do not edit by hand.",
        f"# layout tests for: {main_module_name}",
        "",
        "from std.sys.info import align_of, size_of",
        "from std.reflection import reflect",
    ]
    if checks:
        imported = ", ".join(record.record_name for record in checks)
        lines.append(f"from {main_module_name} import {imported}")
    lines.extend(
        [
            "",
            "",
            "def _check_eq(label: String, got: Int, expected: Int) raises:",
            "    if got != expected:",
            '        raise Error(label + ": got " + String(got) + ", expected " + String(expected))',
        ]
    )

    for record in checks:
        lines.extend(["", "", f"def test_layout_{record.record_name}() raises:"])
        lines.append(f"    comptime r = reflect[{record.record_name}]()")
        for check in record.checks:
            lines.append(
                f'    _check_eq("{check.label}", Int({check.expression}), {check.expected})'
            )
        if not record.checks:
            lines.append("    pass")

    lines.extend(["", "", "def main() raises:"])
    if checks:
        for record in checks:
            lines.append(f"    test_layout_{record.record_name}()")
    else:
        lines.append("    pass")
    return "\n".join(lines) + "\n"


__all__ = [
    "LayoutCheck",
    "LayoutRecordCheck",
    "collect_layout_record_checks",
    "render_layout_test_module",
]
