# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/callback_typedef_alias/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call
from std.ffi import external_call
from std.memory import ImmutOpaquePointer, MutOpaquePointer

comptime cta_cb_t = def (arg0: Int32) abi("C") -> Int32

def cta_install(cb: UnsafePointer[cta_cb_t, MutExternalOrigin]) abi("C") -> None:
    external_call["cta_install", NoneType, UnsafePointer[cta_cb_t, MutExternalOrigin]](cb)

