# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/callback_typedef_alias/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call, c_int

comptime int32_t = c_int

comptime cta_cb_t = def (value: int32_t) thin abi("C") -> int32_t

def cta_install(cb: cta_cb_t) abi("C") -> None:
    external_call["cta_install", NoneType, cta_cb_t](cb)
