# Generated by mojo_bindgen - do not edit by hand.
# source: tests/stress/normal/stress_normal_input.h
# library: stress_normal  link_name: stress_normal
# FFI mode: external_call
# NOTE: some atomic types were mapped to their underlying non-atomic Mojo type because Atomic[dtype] was not representable
# NOTE: some complex C types were mapped as InlineArray[scalar, 2] because ComplexSIMD[dtype, 1] was not representable
from std.ffi import external_call, OwnedDLHandle, DEFAULT_RTLD, UnsafeUnion, c_char, c_double, c_float, c_int, c_long, c_long_long, c_short, c_uchar, c_uint, c_ulong, c_ulong_long, c_ushort
from std.memory import ImmutOpaquePointer, MutOpaquePointer
from std.builtin.simd import SIMD
from std.complex import ComplexSIMD
from std.atomic import Atomic

# Resolve symbols from libraries already linked into this process (e.g. mojo link step).
def _bindgen_dl() raises -> OwnedDLHandle:
    return OwnedDLHandle(DEFAULT_RTLD)

struct GlobalVar[T: Copyable & ImplicitlyDestructible, //, link: StaticString]:
    @staticmethod
    def _raw() raises -> UnsafePointer[Self.T, MutAnyOrigin]:
        var opt: Optional[UnsafePointer[Self.T, MutAnyOrigin]] = _bindgen_dl().get_symbol[Self.T](StringSlice(Self.link))
        if not opt:
            raise Error(String("bindgen: missing C global symbol"))
        return opt.value()

    @staticmethod
    def ptr() raises -> UnsafePointer[Self.T, MutExternalOrigin]:
        return rebind[UnsafePointer[Self.T, MutExternalOrigin]](Self._raw())

    @staticmethod
    def load() raises -> Self.T:
        return Self._raw()[].copy()

    @staticmethod
    def store(value: Self.T) raises -> None:
        var p = rebind[UnsafePointer[Self.T, MutExternalOrigin]](Self._raw())
        p[] = value.copy()


struct GlobalConst[T: Copyable & ImplicitlyDestructible, //, link: StaticString]:
    @staticmethod
    def _raw() raises -> UnsafePointer[Self.T, MutAnyOrigin]:
        var opt: Optional[UnsafePointer[Self.T, MutAnyOrigin]] = _bindgen_dl().get_symbol[Self.T](StringSlice(Self.link))
        if not opt:
            raise Error(String("bindgen: missing C global symbol"))
        return opt.value()

    @staticmethod
    def ptr() raises -> UnsafePointer[Self.T, ImmutExternalOrigin]:
        return rebind[UnsafePointer[Self.T, ImmutExternalOrigin]](Self._raw())

    @staticmethod
    def load() raises -> Self.T:
        return Self._raw()[].copy()


# incomplete C struct `max_align_t` — opaque; use only as pointer target
@fieldwise_init
struct max_align_t(Copyable, Movable):
    pass
# incomplete C struct `ev_loop` — opaque; use only as pointer target
@fieldwise_init
struct ev_loop(Copyable, Movable):
    pass
# incomplete C struct `ev_watcher` — opaque; use only as pointer target
@fieldwise_init
struct ev_watcher(Copyable, Movable):
    pass
# incomplete C struct `ev_incomplete_only` — opaque; use only as pointer target
@fieldwise_init
struct ev_incomplete_only(Copyable, Movable):
    pass
comptime ev_watcher_list_cb = def (arg0: UnsafePointer[ev_loop, MutExternalOrigin]) thin abi("C") -> NoneType

comptime ev_cb_t = def (arg0: UnsafePointer[ev_loop, MutExternalOrigin], arg1: MutOpaquePointer[MutExternalOrigin], arg2: c_int) thin abi("C") -> NoneType

comptime ev_void_fn_t = def () thin abi("C") -> NoneType

comptime ev_unary_int_fn_t = def (arg0: c_int) thin abi("C") -> c_int

comptime ev_binary_int_fn_t = def (arg0: c_int, arg1: c_int) thin abi("C") -> c_int

comptime ev_ret_int_ptr_fn_t = def (arg0: UnsafePointer[c_int, MutExternalOrigin]) thin abi("C") -> UnsafePointer[c_int, MutExternalOrigin]

comptime ev_array_param_fn_t = def (arg0: UnsafePointer[c_int, MutExternalOrigin]) thin abi("C") -> NoneType

comptime ev_vla_param_fn_t = def (arg0: c_ulong, arg1: UnsafePointer[c_int, MutExternalOrigin]) thin abi("C") -> c_int

comptime ev_loop_transform_cb_t = def (arg0: UnsafePointer[ev_loop, MutExternalOrigin], arg1: MutOpaquePointer[MutExternalOrigin], arg2: c_int) thin abi("C") -> c_int

comptime ev_callbacks_on_start_cb = def () thin abi("C") -> NoneType

comptime ev_callbacks_transform_cb = def (arg0: c_int) thin abi("C") -> c_int

comptime ev_callbacks_watcher_cb = def (arg0: UnsafePointer[ev_loop, MutExternalOrigin], arg1: MutOpaquePointer[MutExternalOrigin], arg2: c_int) thin abi("C") -> NoneType

comptime ev_callbacks_cmp_cb = def (arg0: ImmutOpaquePointer[ImmutExternalOrigin], arg1: ImmutOpaquePointer[ImmutExternalOrigin]) thin abi("C") -> c_int

comptime ev_choose_binary_op_return_cb = def (arg0: c_int, arg1: c_int) thin abi("C") -> c_int

comptime ev_accept_fn_fn_cb = def (arg0: c_int) thin abi("C") -> c_int

comptime ev_get_transformer_return_cb = def (arg0: c_int) thin abi("C") -> c_int

comptime ev_embedded_fnptrs_start_cb = def () thin abi("C") -> NoneType

comptime ev_embedded_fnptrs_stop_cb = def (arg0: MutOpaquePointer[MutExternalOrigin]) thin abi("C") -> NoneType

comptime ev_embedded_fnptrs_poll_cb = def (arg0: UnsafePointer[ev_loop, MutExternalOrigin], arg1: c_int) thin abi("C") -> c_int

comptime EV_UNDEF = c_int(-1)

comptime EV_NONE = c_int(0)

comptime EV_READ = c_int(1)

comptime EV_WRITE = c_int(2)

# macro STRESS_NORMAL_INPUT_H: empty macro body
# define STRESS_NORMAL_INPUT_H

comptime EV_VERSION_MAJOR = c_int(4)

comptime EV_VERSION_MINOR = c_int(33)

comptime EV_MAXPRI = c_int(9)

comptime EV_FLAG_AUTO = c_uint(1)

comptime EV_FLAG_DYNAMIC = c_uint(2)

comptime EV_FLAG_MASK = c_uint(65535)

# macro EV_STRINGIFY_: function-like macros are preserved but not parsed
# define EV_STRINGIFY_ ( x ) # x

# macro EV_STRINGIFY: function-like macros are preserved but not parsed
# define EV_STRINGIFY ( x ) EV_STRINGIFY_ ( x )

# macro EV_JOIN_: function-like macros are preserved but not parsed
# define EV_JOIN_ ( a , b ) a ## b

# macro EV_JOIN: function-like macros are preserved but not parsed
# define EV_JOIN ( a , b ) EV_JOIN_ ( a , b )

# macro EV_TYPE: identifier reference macro is not emitted directly; only literal macros are currently supported
# define EV_TYPE int

comptime EV_ARRAY_LEN = c_int(16)

comptime EV_NAME_LITERAL = "stress-normal-input"

# -- C union `ev_any_watcher` - not emitted as a struct.
# By-value uses InlineArray[UInt8, 48] unless you wrap a manual UnsafeUnion (unique trivial members).
# C size=48 bytes, align=8.
# Members (reference only):
#   io: ev_io
#   stat: ev_stat
# -- C union `ev_nested_anon__anon_union_1` - not emitted as a struct.
# By-value uses InlineArray[UInt8, 4] unless you wrap a manual UnsafeUnion (unique trivial members).
# C size=4 bytes, align=4.
# Members (reference only):
#   u32: c_uint
#   f32: c_float
#   (anonymous): ev_nested_anon__anon_union_1__anon_struct_1
# -- C union `ev_deep_node__anon_union_1` - not emitted as a struct.
# By-value uses InlineArray[UInt8, 4] unless you wrap a manual UnsafeUnion (unique trivial members).
# C size=4 bytes, align=4.
# Members (reference only):
#   as_int: c_int
#   pair: ev_deep_node__anon_union_1__anon_struct_1
comptime ev_recursive_tree__anon_union_1_Union = UnsafeUnion[c_int, c_double, MutOpaquePointer[MutExternalOrigin]]

# -- C union `ev_recursive_tree__anon_union_1` - comptime `ev_recursive_tree__anon_union_1_Union` = UnsafeUnion[...] (trivial members; see std.ffi).
# C size=8 bytes, align=8.
# Members (reference only):
#   i: c_int
#   d: c_double
#   p: MutOpaquePointer[MutExternalOrigin]
# -- C union `ev_bits_overlay` - not emitted as a struct.
# By-value uses InlineArray[UInt8, 8] unless you wrap a manual UnsafeUnion (unique trivial members).
# C size=8 bytes, align=4.
# Members (reference only):
#   bits: ev_bits
#   raw: c_uint
comptime ev_number_Union = UnsafeUnion[c_int, c_uint, c_long, c_float, c_double, MutOpaquePointer[MutExternalOrigin]]

# -- C union `ev_number` - comptime `ev_number_Union` = UnsafeUnion[...] (trivial members; see std.ffi).
# C size=8 bytes, align=8.
# Members (reference only):
#   i: c_int
#   u: c_uint
#   l: c_long
#   f: c_float
#   d: c_double
#   p: MutOpaquePointer[MutExternalOrigin]
comptime ev_ptr_cast_Union = UnsafeUnion[MutOpaquePointer[MutExternalOrigin], ImmutOpaquePointer[ImmutExternalOrigin], c_ulong, UnsafePointer[c_char, MutExternalOrigin], UnsafePointer[c_int, MutExternalOrigin]]

# -- C union `ev_ptr_cast` - comptime `ev_ptr_cast_Union` = UnsafeUnion[...] (trivial members; see std.ffi).
# C size=8 bytes, align=8.
# Members (reference only):
#   vp: MutOpaquePointer[MutExternalOrigin]
#   cvp: ImmutOpaquePointer[ImmutExternalOrigin]
#   addr: c_ulong
#   cp: UnsafePointer[c_char, MutExternalOrigin]
#   ip: UnsafePointer[c_int, MutExternalOrigin]
# -- C union `ev_incomplete_union` - not emitted as a struct.
# By-value uses InlineArray[UInt8, 0] unless you wrap a manual UnsafeUnion (unique trivial members).
# C size=0 bytes, align=0.
# Members (reference only):
comptime ev_typedef_union_Union = UnsafeUnion[c_int, c_float]

# -- C union `ev_typedef_union` - comptime `ev_typedef_union_Union` = UnsafeUnion[...] (trivial members; see std.ffi).
# C size=4 bytes, align=4.
# Members (reference only):
#   i: c_int
#   f: c_float
# -- C union `ev_vector_union` - not emitted as a struct.
# By-value uses InlineArray[UInt8, 16] unless you wrap a manual UnsafeUnion (unique trivial members).
# C size=16 bytes, align=16.
# Members (reference only):
#   vi: SIMD[DType.int32, 4]
#   vf: SIMD[DType.float32, 4]
#   scalars: InlineArray[c_int, 4]
#   lanes: InlineArray[c_float, 4]
comptime ev_designated__anon_union_1_Union = UnsafeUnion[c_int, c_double]

# -- C union `ev_designated__anon_union_1` - comptime `ev_designated__anon_union_1_Union` = UnsafeUnion[...] (trivial members; see std.ffi).
# C size=8 bytes, align=8.
# Members (reference only):
#   i: c_int
#   d: c_double
# -- C union `ev_nested_union` - not emitted as a struct.
# By-value uses InlineArray[UInt8, 8] unless you wrap a manual UnsafeUnion (unique trivial members).
# C size=8 bytes, align=8.
# Members (reference only):
#   bytes: ev_nested_union__anon_struct_1
#   raw64: c_ulong
#   as_double: c_double
comptime ev_tagged_payload__anon_union_1_Union = UnsafeUnion[c_int, c_float, MutOpaquePointer[MutExternalOrigin]]

# -- C union `ev_tagged_payload__anon_union_1` - comptime `ev_tagged_payload__anon_union_1_Union` = UnsafeUnion[...] (trivial members; see std.ffi).
# C size=8 bytes, align=8.
# Members (reference only):
#   i: c_int
#   f: c_float
#   p: MutOpaquePointer[MutExternalOrigin]
# struct ev_tstamp_pair - size=16 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_tstamp_pair(Copyable, Movable, RegisterPassable):
    var at: c_double
    var repeat: c_double
# struct ev_io - size=24 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_io(Copyable, Movable, RegisterPassable):
    var active: c_int
    var pending: c_int
    var data: MutOpaquePointer[MutExternalOrigin]
    var fd: c_int
    var events: c_int
# struct ev_prepare_batch - size=136 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_prepare_batch(Copyable, Movable):
    var watchers: InlineArray[MutOpaquePointer[MutExternalOrigin], 16]
    var count: c_int
    var id: InlineArray[c_uchar, 4]
# struct ev_watcher_list - size=24 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_watcher_list(Copyable, Movable):
    var next: UnsafePointer[ev_watcher, MutExternalOrigin]
    var cb: UnsafePointer[ev_watcher_list_cb, MutExternalOrigin]
    var data: MutOpaquePointer[MutExternalOrigin]
# struct ev_packet - size=8 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_packet(Copyable, Movable, RegisterPassable):
    var length: c_int
    var type: c_int
    var payload: UnsafePointer[c_uchar, MutExternalOrigin]
# struct ev_packed_header - size=5 align=1 (verify packed/aligned ABI)
@fieldwise_init
struct ev_packed_header(Copyable, Movable, RegisterPassable):
    var flag: c_uchar
    var length: c_uint
# struct ev_aligned_data - size=32 align=16 (verify packed/aligned ABI)
@align(16)
@fieldwise_init
struct ev_aligned_data(Copyable, Movable, RegisterPassable):
    var a: c_char
    var b: c_int
# struct ev_matrix - size=64 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_matrix(Copyable, Movable):
    var transform: InlineArray[InlineArray[c_float, 4], 4]
# struct ev_node - size=16 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_node(Copyable, Movable):
    var next: UnsafePointer[ev_node, MutExternalOrigin]
    var prev: UnsafePointer[ev_node, MutExternalOrigin]
# struct ev_a - size=8 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_a(Copyable, Movable):
    var next: UnsafePointer[ev_a, MutExternalOrigin]
# struct ev_pad - size=12 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_pad(Copyable, Movable, RegisterPassable):
    var a: c_char
    var b: c_int
    var c: c_char
# struct ev_array_holder - size=104 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_array_holder(Copyable, Movable):
    var fixed: InlineArray[c_int, 8]
    var matrix: InlineArray[InlineArray[c_int, 3], 2]
    var names: InlineArray[UnsafePointer[c_char, ImmutExternalOrigin], 4]
    var bytes: InlineArray[c_uchar, 16]
# struct ev_callbacks - size=40 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_callbacks(Copyable, Movable, RegisterPassable):
    var on_start: UnsafePointer[ev_callbacks_on_start_cb, MutExternalOrigin]
    var transform: UnsafePointer[ev_callbacks_transform_cb, MutExternalOrigin]
    var vlog: ev_variadic_cb_t
    var watcher_cb: UnsafePointer[ev_callbacks_watcher_cb, MutExternalOrigin]
    var cmp: UnsafePointer[ev_callbacks_cmp_cb, MutExternalOrigin]
# struct ev_nested_anon__anon_struct_1 - size=8 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_nested_anon__anon_struct_1(Copyable, Movable, RegisterPassable):
    var x: c_int
    var y: c_int
# struct ev_nested_anon__anon_union_1__anon_struct_1 - size=4 align=2 (verify packed/aligned ABI)
@align(2)
@fieldwise_init
struct ev_nested_anon__anon_union_1__anon_struct_1(Copyable, Movable, RegisterPassable):
    var lo: c_ushort
    var hi: c_ushort
# struct ev_deep_node__anon_union_1__anon_struct_1 - size=4 align=2 (verify packed/aligned ABI)
@align(2)
@fieldwise_init
struct ev_deep_node__anon_union_1__anon_struct_1(Copyable, Movable, RegisterPassable):
    var left: c_short
    var right: c_short
# struct ev_deep_node - size=16 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_deep_node(Copyable, Movable):
    var next: UnsafePointer[ev_deep_node, MutExternalOrigin]
    var payload: InlineArray[UInt8, 4]
# struct ev_recursive_tree - size=24 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_recursive_tree(Copyable, Movable):
    var left: UnsafePointer[ev_recursive_tree, MutExternalOrigin]
    var right: UnsafePointer[ev_recursive_tree, MutExternalOrigin]
    var value: ev_recursive_tree__anon_union_1_Union
# struct ev_bits - size=8 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_bits(Copyable, Movable, RegisterPassable):
    # bitfield: C bits 0..0 (1 bits) on UINT
    # ABI: verify bitfield layout matches target C compiler.
    var ready: c_uint
    # bitfield: C bits 1..1 (1 bits) on UINT
    # ABI: verify bitfield layout matches target C compiler.
    var error: c_uint
    # bitfield: C bits 2..4 (3 bits) on UINT
    # ABI: verify bitfield layout matches target C compiler.
    var state: c_uint
    # bitfield: C bits 5..15 (11 bits) on UINT
    # ABI: verify bitfield layout matches target C compiler.
    var code: c_uint
    # bitfield: C bits 32..31 (0 bits) on UINT
    # ABI: verify bitfield layout matches target C compiler.
    var _anon_4: c_uint
    # bitfield: C bits 32..38 (7 bits) on INT
    # ABI: verify bitfield layout matches target C compiler.
    var delta: c_int
    # bitfield: C bits 39..39 (1 bits) on BOOL
    # ABI: verify bitfield layout matches target C compiler.
    var enabled: Bool
# struct ev_blob - size=8 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_blob(Copyable, Movable, RegisterPassable):
    var size: c_ulong
    var data: UnsafePointer[c_uchar, MutExternalOrigin]
# struct ev_blob0 - size=8 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_blob0(Copyable, Movable):
    var size: c_ulong
    var data: InlineArray[c_uchar, 0]
# struct ev_atomic_holder - size=16 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_atomic_holder(Copyable, Movable):
    var counter: Atomic[DType.int32]
    var flags: Atomic[DType.uint32]
    var user: MutOpaquePointer[MutExternalOrigin]
# struct ev_complex_pair - size=24 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_complex_pair(Copyable, Movable, RegisterPassable):
    var z0: ComplexSIMD[DType.float64, 1]
    var z1: ComplexSIMD[DType.float32, 1]
# struct ev_alignas_block - size=64 align=32 (verify packed/aligned ABI)
@align(32)
@fieldwise_init
struct ev_alignas_block(Copyable, Movable):
    var storage: InlineArray[c_uchar, 32]
    var lanes: InlineArray[c_int, 4]
# struct ev_gnu_packed_bits - size=7 align=1 (verify packed/aligned ABI)
# packed record: verify Mojo layout against the target C ABI.
@fieldwise_init
struct ev_gnu_packed_bits(Copyable, Movable, RegisterPassable):
    var a: c_uchar
    var b: c_ushort
    var c: c_uint
# struct ev_cacheline_block - size=64 align=64 (verify packed/aligned ABI)
@align(64)
@fieldwise_init
struct ev_cacheline_block(Copyable, Movable):
    var payload: InlineArray[c_uchar, 64]
# struct ev_typedef_struct - size=4 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_typedef_struct(Copyable, Movable, RegisterPassable):
    var value: c_int
# struct ev_cv_payload - size=32 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_cv_payload(Copyable, Movable, RegisterPassable):
    var a: UnsafePointer[c_int, ImmutExternalOrigin]
    var b: UnsafePointer[c_int, MutExternalOrigin]
    var c: UnsafePointer[c_int, ImmutExternalOrigin]
    var pinned: UnsafePointer[c_int, MutExternalOrigin]
# struct ev_i128_box - size=32 align=16 (verify packed/aligned ABI)
@align(16)
@fieldwise_init
struct ev_i128_box(Copyable, Movable, RegisterPassable):
    var lohi: Int128
    var ulohi: UInt128
# struct ev_designated__anon_struct_1 - size=8 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_designated__anon_struct_1(Copyable, Movable, RegisterPassable):
    var major: c_int
    var minor: c_int
# struct ev_mixed_layout - size=40 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_mixed_layout(Copyable, Movable, RegisterPassable):
    var c0: c_char
    var d0: c_double
    var s0: c_short
    var p0: MutOpaquePointer[MutExternalOrigin]
    var c1: c_char
# struct ev_nested_union__anon_struct_1 - size=8 align=1 (verify packed/aligned ABI)
@fieldwise_init
struct ev_nested_union__anon_struct_1(Copyable, Movable):
    var tag: c_uchar
    var payload: InlineArray[c_uchar, 7]
# struct ev_embedded_fnptrs - size=24 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_embedded_fnptrs(Copyable, Movable, RegisterPassable):
    var start: UnsafePointer[ev_embedded_fnptrs_start_cb, MutExternalOrigin]
    var stop: UnsafePointer[ev_embedded_fnptrs_stop_cb, MutExternalOrigin]
    var poll: UnsafePointer[ev_embedded_fnptrs_poll_cb, MutExternalOrigin]
# struct ev_tagged_payload - size=16 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_tagged_payload(Copyable, Movable):
    var kind: ev_payload_kind
    var as_: ev_tagged_payload__anon_union_1_Union
# struct ev_text - size=192 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_text(Copyable, Movable):
    var ascii: InlineArray[c_char, 32]
    var wide: InlineArray[c_int, 16]
    var utf16: InlineArray[c_ushort, 16]
    var utf32: InlineArray[c_uint, 16]
# struct ev_stat - size=48 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_stat(Copyable, Movable, RegisterPassable):
    var prev: ev_tstamp_pair
    var curr: ev_tstamp_pair
    var path: UnsafePointer[c_char, ImmutExternalOrigin]
    var interval: c_uint
# struct ev_nested_anon - size=16 align=4 (verify packed/aligned ABI)
@align(4)
@fieldwise_init
struct ev_nested_anon(Copyable, Movable):
    var tag: c_int
    var _anon_1: ev_nested_anon__anon_struct_1
    var _anon_2: InlineArray[UInt8, 4]
# struct ev_designated - size=32 align=8 (verify packed/aligned ABI)
@align(8)
@fieldwise_init
struct ev_designated(Copyable, Movable):
    var id: c_int
    var name: UnsafePointer[c_char, ImmutExternalOrigin]
    var version: ev_designated__anon_struct_1
    var data: ev_designated__anon_union_1_Union
# enum ev_backend - underlying UINT -> c_uint (verify C ABI)
@fieldwise_init
struct ev_backend(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime EVBACKEND_SELECT = Self(c_uint(1))
    comptime EVBACKEND_POLL = Self(c_uint(2))
    comptime EVBACKEND_EPOLL = Self(c_uint(4))
    comptime EVBACKEND_MASK = Self(c_uint(65535))
# enum ev_run_flags - underlying UINT -> c_uint (verify C ABI)
@fieldwise_init
struct ev_run_flags(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime EVRUN_NOWAIT = Self(c_uint(1))
    comptime EVRUN_ONCE = Self(c_uint(2))
comptime ev_any_watcher = InlineArray[UInt8, 48]

comptime ev_tstamp = c_double

comptime ev_time_t = ev_tstamp

comptime ev_eventmask = c_uint

comptime ev_loop_ptr = UnsafePointer[ev_loop, MutExternalOrigin]

def ev_version_major() abi("C") -> c_uint:
    return external_call["ev_version_major", c_uint]()

def ev_loop_new(flags: c_uint) abi("C") -> UnsafePointer[ev_loop, MutExternalOrigin]:
    return external_call["ev_loop_new", UnsafePointer[ev_loop, MutExternalOrigin], c_uint](flags)

def ev_io_init(w: UnsafePointer[ev_io, MutExternalOrigin], cb: UnsafePointer[ev_cb_t, MutExternalOrigin], fd: c_int, events: c_int) abi("C") -> None:
    external_call["ev_io_init", NoneType, UnsafePointer[ev_io, MutExternalOrigin], UnsafePointer[ev_cb_t, MutExternalOrigin], c_int, c_int](w, cb, fd, events)

def ev_stat_path_watch(w: UnsafePointer[ev_stat, ImmutExternalOrigin], path: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["ev_stat_path_watch", c_int, UnsafePointer[ev_stat, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin]](w, path)

def ev_now_pair(loop: UnsafePointer[ev_loop, MutExternalOrigin]) abi("C") -> ev_tstamp_pair:
    return external_call["ev_now_pair", ev_tstamp_pair, UnsafePointer[ev_loop, MutExternalOrigin]](loop)

# variadic C function - not callable from thin FFI:
# NoneType ev_set_userdata(loop: UnsafePointer[ev_loop, MutExternalOrigin], data: MutOpaquePointer[MutExternalOrigin], ...)
def ev_feed_event_batch(loop: UnsafePointer[ev_loop, MutExternalOrigin], events: UnsafePointer[c_int, MutExternalOrigin], count: c_int) abi("C") -> None:
    external_call["ev_feed_event_batch", NoneType, UnsafePointer[ev_loop, MutExternalOrigin], UnsafePointer[c_int, MutExternalOrigin], c_int](loop, events, count)

def ev_get_version_string(out_version: UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin]) abi("C") -> None:
    external_call["ev_get_version_string", NoneType, UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin]](out_version)

def ev_process_argv(argc: c_int, argv: UnsafePointer[UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin], MutExternalOrigin]) abi("C") -> c_int:
    return external_call["ev_process_argv", c_int, c_int, UnsafePointer[UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin], MutExternalOrigin]](argc, argv)

# global `ev_global_error_code` -> c_int
comptime ev_global_error_code = GlobalVar[T=c_int, link="ev_global_error_code"]

# global `ev_backend_name` -> UnsafePointer[c_char, ImmutExternalOrigin]
comptime ev_backend_name = GlobalVar[T=UnsafePointer[c_char, ImmutExternalOrigin], link="ev_backend_name"]

def ev_is_active(loop: UnsafePointer[ev_loop, MutExternalOrigin]) abi("C") -> Bool:
    return external_call["ev_is_active", Bool, UnsafePointer[ev_loop, MutExternalOrigin]](loop)

def ev_atomic_add(counter: UnsafePointer[c_int, MutExternalOrigin], amount: c_int) abi("C") -> None:
    external_call["ev_atomic_add", NoneType, UnsafePointer[c_int, MutExternalOrigin], c_int](counter, amount)

def ev_memory_copy(dest: MutOpaquePointer[MutExternalOrigin], src: ImmutOpaquePointer[ImmutExternalOrigin], n: c_ulong) abi("C") -> None:
    external_call["ev_memory_copy", NoneType, MutOpaquePointer[MutExternalOrigin], ImmutOpaquePointer[ImmutExternalOrigin], c_ulong](dest, src, n)

comptime ev_dynamic_t = c_int

# global `ev_internal_state` -> c_int
comptime ev_internal_state = GlobalVar[T=c_int, link="ev_internal_state"]

# global `ev_default_loop` -> UnsafePointer[ev_loop, ImmutExternalOrigin]
comptime ev_default_loop = GlobalVar[T=UnsafePointer[ev_loop, ImmutExternalOrigin], link="ev_default_loop"]

comptime ev_i8 = c_char

comptime ev_u8 = c_uchar

comptime ev_i16 = c_short

comptime ev_u16 = c_ushort

comptime ev_i32 = c_int

comptime ev_u32 = c_uint

comptime ev_long_t = c_long

comptime ev_ulong_t = c_ulong

comptime ev_i64 = c_long_long

comptime ev_u64 = c_ulong_long

comptime ev_f32 = c_float

comptime ev_f64 = c_double

comptime ev_f128ish = Float64

comptime ev_char_t = c_char

comptime ev_schar_t = c_char

comptime ev_uchar_t = c_uchar

comptime ev_wchar_t = c_int

comptime ev_char16_t = c_ushort

comptime ev_char32_t = c_uint

comptime ev_intptr_t = c_long

comptime ev_uintptr_t = c_ulong

comptime ev_ptrdiff_t = c_long

comptime ev_size_t = c_ulong

comptime ev_max_align_t = max_align_t

comptime ev_const_int_t = c_int

comptime ev_volatile_int_t = c_int

comptime ev_cv_int_t = c_int

comptime ev_int_ptr = UnsafePointer[c_int, MutExternalOrigin]

comptime ev_const_int_ptr = UnsafePointer[c_int, ImmutExternalOrigin]

comptime ev_const_ptr_to_int = UnsafePointer[c_int, MutExternalOrigin]

comptime ev_const_ptr_to_const_int = UnsafePointer[c_int, ImmutExternalOrigin]

comptime ev_volatile_int_ptr = UnsafePointer[c_int, MutExternalOrigin]

comptime ev_cv_int_ptr = UnsafePointer[c_int, ImmutExternalOrigin]

comptime ev_bool_alias = Bool

# enum ev_small_enum - underlying UINT -> c_uint (verify C ABI)
@fieldwise_init
struct ev_small_enum(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime EV_SMALL_ZERO = Self(c_uint(0))
    comptime EV_SMALL_ONE = Self(c_uint(1))
comptime ev_backend_alias = ev_backend

comptime ev_run_flags_alias = ev_run_flags

comptime ev_int_array_4 = InlineArray[c_int, 4]

comptime ev_int_matrix_3x5 = InlineArray[InlineArray[c_int, 5], 3]

comptime ev_string_table_2x3 = InlineArray[InlineArray[UnsafePointer[c_char, ImmutExternalOrigin], 3], 2]

comptime ev_variadic_cb_t = MutOpaquePointer[MutExternalOrigin]

comptime ev_bits_overlay = InlineArray[UInt8, 8]

comptime ev_atomic_int_t = Atomic[DType.int32]

comptime ev_atomic_uint_t = Atomic[DType.uint32]

comptime ev_atomic_void_ptr_t = MutOpaquePointer[MutExternalOrigin]

# global variable ev_global_atomic_counter: Atomic[DType.int32] (atomic global requires manual binding (use Atomic APIs on a pointer))

# global `ev_mmio_status_reg` -> c_uint
comptime ev_mmio_status_reg = GlobalVar[T=c_uint, link="ev_mmio_status_reg"]

# global `ev_mmio_base` -> UnsafePointer[c_uint, ImmutExternalOrigin]
comptime ev_mmio_base = GlobalVar[T=UnsafePointer[c_uint, ImmutExternalOrigin], link="ev_mmio_base"]

comptime ev_cfloat = ComplexSIMD[DType.float32, 1]

comptime ev_cdouble = ComplexSIMD[DType.float64, 1]

comptime ev_cldouble = InlineArray[Float64, 2]

comptime ev_row4_t = InlineArray[c_int, 4]

comptime ev_matrix2x4_t = InlineArray[ev_row4_t, 2]

comptime ev_row_ptr_t = UnsafePointer[InlineArray[c_int, 4], MutExternalOrigin]

comptime ev_signal_table_t = InlineArray[MutOpaquePointer[MutExternalOrigin], 3]

comptime ev_number = ev_number_Union

comptime ev_ptr_cast = ev_ptr_cast_Union

comptime ev_incomplete_only_t = ev_incomplete_only

comptime ev_incomplete_union_t = InlineArray[UInt8, 0]

comptime ev_typedef_union = ev_typedef_union_Union

# enum ev_typedef_enum - underlying UINT -> c_uint (verify C ABI)
@fieldwise_init
struct ev_typedef_enum(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime EV_TENUM_A = Self(c_uint(1))
    comptime EV_TENUM_B = Self(c_uint(2))
comptime ev_const_arr_4 = InlineArray[c_int, 4]

comptime ev_volatile_arr_4 = InlineArray[c_int, 4]

comptime ev_cv_arr_4 = InlineArray[c_int, 4]

comptime ev_i128 = Int128

comptime ev_u128 = UInt128

comptime ev_v4si = SIMD[DType.int32, 4]

comptime ev_v4sf = SIMD[DType.float32, 4]

comptime ev_vector_union = InlineArray[UInt8, 16]

def ev_take_const_ptr(p: UnsafePointer[c_int, ImmutExternalOrigin]) abi("C") -> None:
    external_call["ev_take_const_ptr", NoneType, UnsafePointer[c_int, ImmutExternalOrigin]](p)

def ev_take_const_ptr_const(p: UnsafePointer[c_int, ImmutExternalOrigin]) abi("C") -> None:
    external_call["ev_take_const_ptr_const", NoneType, UnsafePointer[c_int, ImmutExternalOrigin]](p)

def ev_take_cv_ptr(p: UnsafePointer[c_int, ImmutExternalOrigin]) abi("C") -> None:
    external_call["ev_take_cv_ptr", NoneType, UnsafePointer[c_int, ImmutExternalOrigin]](p)

def ev_take_restrict_buffers(dst: MutOpaquePointer[MutExternalOrigin], src: ImmutOpaquePointer[ImmutExternalOrigin], n: c_ulong) abi("C") -> None:
    external_call["ev_take_restrict_buffers", NoneType, MutOpaquePointer[MutExternalOrigin], ImmutOpaquePointer[ImmutExternalOrigin], c_ulong](dst, src, n)

def ev_sum_fixed4(a: InlineArray[c_int, 4]) abi("C") -> c_int:
    return external_call["ev_sum_fixed4", c_int, InlineArray[c_int, 4]](a)

def ev_sum_static4(a: InlineArray[c_int, 4]) abi("C") -> c_int:
    return external_call["ev_sum_static4", c_int, InlineArray[c_int, 4]](a)

def ev_sum_vla(n: c_ulong, a: UnsafePointer[c_int, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["ev_sum_vla", c_int, c_ulong, UnsafePointer[c_int, MutExternalOrigin]](n, a)

def ev_fill_vla(n: c_ulong, a: UnsafePointer[c_int, MutExternalOrigin], value: c_int) abi("C") -> None:
    external_call["ev_fill_vla", NoneType, c_ulong, UnsafePointer[c_int, MutExternalOrigin], c_int](n, a, value)

def ev_choose_binary_op(a0: c_int, a1: c_int, which: c_int) abi("C") -> UnsafePointer[ev_choose_binary_op_return_cb, MutExternalOrigin]:
    return external_call["ev_choose_binary_op", UnsafePointer[ev_choose_binary_op_return_cb, MutExternalOrigin], c_int, c_int, c_int](a0, a1, which)

def ev_get_signal_table() abi("C") -> UnsafePointer[InlineArray[c_int, 3], MutExternalOrigin]:
    return external_call["ev_get_signal_table", UnsafePointer[InlineArray[c_int, 3], MutExternalOrigin]]()

def ev_accept_fn(fn_: UnsafePointer[ev_accept_fn_fn_cb, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["ev_accept_fn", c_int, UnsafePointer[ev_accept_fn_fn_cb, MutExternalOrigin]](fn_)

def ev_accept_variadic(fn_: MutOpaquePointer[MutExternalOrigin]) abi("C") -> c_int:
    return external_call["ev_accept_variadic", c_int, MutOpaquePointer[MutExternalOrigin]](fn_)

def ev_get_name() abi("C") -> UnsafePointer[c_char, ImmutExternalOrigin]:
    return external_call["ev_get_name", UnsafePointer[c_char, ImmutExternalOrigin]]()

def ev_get_context(loop: UnsafePointer[ev_loop, MutExternalOrigin]) abi("C") -> MutOpaquePointer[MutExternalOrigin]:
    return external_call["ev_get_context", MutOpaquePointer[MutExternalOrigin], UnsafePointer[ev_loop, MutExternalOrigin]](loop)

def ev_get_const_loop() abi("C") -> UnsafePointer[ev_loop, ImmutExternalOrigin]:
    return external_call["ev_get_const_loop", UnsafePointer[ev_loop, ImmutExternalOrigin]]()

def ev_get_counter_ptr() abi("C") -> UnsafePointer[c_int, MutExternalOrigin]:
    return external_call["ev_get_counter_ptr", UnsafePointer[c_int, MutExternalOrigin]]()

def ev_get_transformer(a0: c_int) abi("C") -> UnsafePointer[ev_get_transformer_return_cb, MutExternalOrigin]:
    return external_call["ev_get_transformer", UnsafePointer[ev_get_transformer_return_cb, MutExternalOrigin], c_int](a0)

def ev_make_pair(at: c_double, repeat: c_double) abi("C") -> ev_tstamp_pair:
    return external_call["ev_make_pair", ev_tstamp_pair, c_double, c_double](at, repeat)

def ev_inline_add(a: c_int, b: c_int) abi("C") -> c_int:
    return external_call["ev_inline_add", c_int, c_int, c_int](a, b)

def ev_fatal(message: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> None:
    external_call["ev_fatal", NoneType, UnsafePointer[c_char, ImmutExternalOrigin]](message)

# global `ev_ptr_array` -> InlineArray[UnsafePointer[c_int, MutExternalOrigin], 3]
comptime ev_ptr_array = GlobalVar[T=InlineArray[UnsafePointer[c_int, MutExternalOrigin], 3], link="ev_ptr_array"]

# global `ev_array_of_fn_ptrs` -> InlineArray[MutOpaquePointer[MutExternalOrigin], 2]
comptime ev_array_of_fn_ptrs = GlobalVar[T=InlineArray[MutOpaquePointer[MutExternalOrigin], 2], link="ev_array_of_fn_ptrs"]

def ev_fn_returning_array_ptr() abi("C") -> UnsafePointer[InlineArray[UnsafePointer[c_int, MutExternalOrigin], 4], MutExternalOrigin]:
    return external_call["ev_fn_returning_array_ptr", UnsafePointer[InlineArray[UnsafePointer[c_int, MutExternalOrigin], 4], MutExternalOrigin]]()

comptime ev_nested_union = InlineArray[UInt8, 8]

# enum ev_payload_kind - underlying UINT -> c_uint (verify C ABI)
@fieldwise_init
struct ev_payload_kind(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime EV_PAYLOAD_INT = Self(c_uint(1))
    comptime EV_PAYLOAD_FLOAT = Self(c_uint(2))
    comptime EV_PAYLOAD_PTR = Self(c_uint(3))
# global `ev_global_counter` -> c_int
comptime ev_global_counter = GlobalVar[T=c_int, link="ev_global_counter"]

# global `ev_global_limit` -> c_int
comptime ev_global_limit = GlobalConst[T=c_int, link="ev_global_limit"]

# global `ev_global_buffer` -> UnsafePointer[c_char, MutExternalOrigin]
comptime ev_global_buffer = GlobalVar[T=UnsafePointer[c_char, MutExternalOrigin], link="ev_global_buffer"]

# global `ev_build_id` -> UnsafePointer[c_char, MutExternalOrigin]
comptime ev_build_id = GlobalVar[T=UnsafePointer[c_char, MutExternalOrigin], link="ev_build_id"]

# global `ev_global_list_head` -> ev_node
comptime ev_global_list_head = GlobalVar[T=ev_node, link="ev_global_list_head"]

# global `ev_global_number` -> ev_number_Union
comptime ev_global_number = GlobalVar[T=ev_number_Union, link="ev_global_number"]

# global `ev_global_callbacks` -> ev_callbacks
comptime ev_global_callbacks = GlobalVar[T=ev_callbacks, link="ev_global_callbacks"]

# global `ev_tls_errno_like` -> c_int
comptime ev_tls_errno_like = GlobalVar[T=c_int, link="ev_tls_errno_like"]

def ev_is_active(loop: UnsafePointer[ev_loop, MutExternalOrigin]) abi("C") -> Bool:
    return external_call["ev_is_active", Bool, UnsafePointer[ev_loop, MutExternalOrigin]](loop)

def ev_atomic_add(counter: UnsafePointer[c_int, MutExternalOrigin], amount: c_int) abi("C") -> None:
    external_call["ev_atomic_add", NoneType, UnsafePointer[c_int, MutExternalOrigin], c_int](counter, amount)

def ev_memory_copy(dest: MutOpaquePointer[MutExternalOrigin], src: ImmutOpaquePointer[ImmutExternalOrigin], n: c_ulong) abi("C") -> None:
    external_call["ev_memory_copy", NoneType, MutOpaquePointer[MutExternalOrigin], ImmutOpaquePointer[ImmutExternalOrigin], c_ulong](dest, src, n)

def ev_store_atomic(dst: UnsafePointer[Atomic[DType.int32], MutExternalOrigin], value: c_int) abi("C") -> None:
    external_call["ev_store_atomic", NoneType, UnsafePointer[Atomic[DType.int32], MutExternalOrigin], c_int](dst, value)

def ev_load_atomic(src: UnsafePointer[Atomic[DType.int32], ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["ev_load_atomic", c_int, UnsafePointer[Atomic[DType.int32], ImmutExternalOrigin]](src)

def ev_swap_numbers(a: UnsafePointer[ev_number, MutExternalOrigin], b: UnsafePointer[ev_number, MutExternalOrigin]) abi("C") -> None:
    external_call["ev_swap_numbers", NoneType, UnsafePointer[ev_number, MutExternalOrigin], UnsafePointer[ev_number, MutExternalOrigin]](a, b)

def ev_blob_total_size(blob: UnsafePointer[ev_blob, ImmutExternalOrigin]) abi("C") -> c_ulong:
    return external_call["ev_blob_total_size", c_ulong, UnsafePointer[ev_blob, ImmutExternalOrigin]](blob)

def ev_call_loop_cb(cb: UnsafePointer[ev_cb_t, MutExternalOrigin], loop: UnsafePointer[ev_loop, MutExternalOrigin], arg: MutOpaquePointer[MutExternalOrigin], revents: c_int) abi("C") -> c_int:
    return external_call["ev_call_loop_cb", c_int, UnsafePointer[ev_cb_t, MutExternalOrigin], UnsafePointer[ev_loop, MutExternalOrigin], MutOpaquePointer[MutExternalOrigin], c_int](cb, loop, arg, revents)

def ev_complex_mul(a: ComplexSIMD[DType.float64, 1], b: ComplexSIMD[DType.float64, 1]) abi("C") -> ComplexSIMD[DType.float64, 1]:
    return external_call["ev_complex_mul", ComplexSIMD[DType.float64, 1], ComplexSIMD[DType.float64, 1], ComplexSIMD[DType.float64, 1]](a, b)

def ev_vector_add_i32(a: ev_v4si, b: ev_v4si) abi("C") -> ev_v4si:
    return external_call["ev_vector_add_i32", SIMD[DType.int32, 4], ev_v4si, ev_v4si](a, b)

