# Generated by mojo_bindgen - do not edit by hand.
# layout tests for: global_consts_bindings

from std.sys.info import align_of, size_of
from std.reflection import reflect
from global_consts_bindings import point, region


def _check_eq(label: String, got: Int, expected: Int) raises:
    if got != expected:
        raise Error(label + ": got " + String(got) + ", expected " + String(expected))


def test_layout_point() raises:
    comptime r = reflect[point]
    _check_eq("point.size", Int(size_of[point]()), 8)
    _check_eq("point.align", Int(align_of[point]()), 4)
    _check_eq("point.x.offset", Int(r.field_offset[name="x"]()), 0)
    _check_eq("point.y.offset", Int(r.field_offset[name="y"]()), 4)


def test_layout_region() raises:
    comptime r = reflect[region]
    _check_eq("region.size", Int(size_of[region]()), 24)
    _check_eq("region.align", Int(align_of[region]()), 8)
    _check_eq("region.origin.offset", Int(r.field_offset[name="origin"]()), 0)
    _check_eq("region.extent.offset", Int(r.field_offset[name="extent"]()), 8)
    _check_eq("region.label.offset", Int(r.field_offset[name="label"]()), 16)


def main() raises:
    test_layout_point()
    test_layout_region()
